In [1]:
from category_encoders import TargetEncoder
from pandas import read_csv

df = read_csv("ml-fundamentals-and-applications-2025-10/final_proj_data.csv")
df.head()

,Var1,Var2,Var3,Var4,Var5,Var6,Var7,Var8,Var9,Var10,...,Var222,Var223,Var224,Var225,Var226,Var227,Var228,Var229,Var230,y
0,NaN,NaN,NaN,NaN,NaN,812.0,14.0,NaN,NaN,NaN,...,catzS2D,jySVZNlOJy,NaN,xG3x,Aoh3,ZI9m,ib5G6X1eUxUn6,mj86,NaN,0
1,NaN,NaN,NaN,NaN,NaN,2688.0,7.0,NaN,NaN,NaN,...,i06ocsg,LM8l689qOp,NaN,kG3k,WqMG,RAYp,55YFVY9,mj86,NaN,0
2,NaN,NaN,NaN,NaN,NaN,1015.0,14.0,NaN,NaN,NaN,...,P6pu4Vl,LM8l689qOp,NaN,kG3k,Aoh3,ZI9m,R4y5gQQWY8OodqDV,am7c,NaN,0
3,NaN,NaN,NaN,NaN,NaN,168.0,0.0,NaN,NaN,NaN,...,BNrD3Yd,LM8l689qOp,NaN,NaN,FSa2,RAYp,F2FyR07IdsN7I,NaN,NaN,0
4,NaN,NaN,NaN,NaN,NaN,14.0,0.0,NaN,NaN,NaN,...,3B1QowC,LM8l689qOp,NaN,NaN,WqMG,RAYp,F2FyR07IdsN7I,NaN,NaN,0

In [2]:
num_cols = df.select_dtypes(include=["number"]).columns.tolist()
num_cols

['Var1',
 'Var2',
 'Var3',
 'Var4',
 'Var5',
 'Var6',
 'Var7',
 'Var8',
 'Var9',
 'Var10',
 'Var11',
 'Var12',
 'Var13',
 'Var14',
 'Var15',
 'Var16',
 'Var17',
 'Var18',
 'Var19',
 'Var20',
 'Var21',
 'Var22',
 'Var23',
 'Var24',
 'Var25',
 'Var26',
 'Var27',
 'Var28',
 'Var29',
 'Var30',
 'Var31',
 'Var32',
 'Var33',
 'Var34',
 'Var35',
 'Var36',
 'Var37',
 'Var38',
 'Var39',
 'Var40',
 'Var41',
 'Var42',
 'Var43',
 'Var44',
 'Var45',
 'Var46',
 'Var47',
 'Var48',
 'Var49',
 'Var50',
 'Var51',
 'Var52',
 'Var53',
 'Var54',
 'Var55',
 'Var56',
 'Var57',
 'Var58',
 'Var59',
 'Var60',
 'Var61',
 'Var62',
 'Var63',
 'Var64',
 'Var65',
 'Var66',
 'Var67',
 'Var68',
 'Var69',
 'Var70',
 'Var71',
 'Var72',
 'Var73',
 'Var74',
 'Var75',
 'Var76',
 'Var77',
 'Var78',
 'Var79',
 'Var80',
 'Var81',
 'Var82',
 'Var83',
 'Var84',
 'Var85',
 'Var86',
 'Var87',
 'Var88',
 'Var89',
 'Var90',
 'Var91',
 'Var92',
 'Var93',
 'Var94',
 'Var95',
 'Var96',
 'Var97',
 'Var98',
 'Var99',
 'Var100',
 'Var101',
 'Var102',
 'Var103',
 'Var104',
 'Var105',
 'Var106',
 'Var107',
 'Var108',
 'Var109',
 'Var110',
 'Var111',
 'Var112',
 'Var113',
 'Var114',
 'Var115',
 'Var116',
 'Var117',
 'Var118',
 'Var119',
 'Var120',
 'Var121',
 'Var122',
 'Var123',
 'Var124',
 'Var125',
 'Var126',
 'Var127',
 'Var128',
 'Var129',
 'Var130',
 'Var131',
 'Var132',
 'Var133',
 'Var134',
 'Var135',
 'Var136',
 'Var137',
 'Var138',
 'Var139',
 'Var140',
 'Var141',
 'Var142',
 'Var143',
 'Var144',
 'Var145',
 'Var146',
 'Var147',
 'Var148',
 'Var149',
 'Var150',
 'Var151',
 'Var152',
 'Var153',
 'Var154',
 'Var155',
 'Var156',
 'Var157',
 'Var158',
 'Var159',
 'Var160',
 'Var161',
 'Var162',
 'Var163',
 'Var164',
 'Var165',
 'Var166',
 'Var167',
 'Var168',
 'Var169',
 'Var170',
 'Var171',
 'Var172',
 'Var173',
 'Var174',
 'Var175',
 'Var176',
 'Var177',
 'Var178',
 'Var179',
 'Var180',
 'Var181',
 'Var182',
 'Var183',
 'Var184',
 'Var185',
 'Var186',
 'Var187',
 'Var188',
 'Var189',
 'Var190',
 'Var209',
 'Var230',
 'y']

In [3]:
cat_cols = df.drop(columns=num_cols).columns.tolist()
cat_cols

['Var191',
 'Var192',
 'Var193',
 'Var194',
 'Var195',
 'Var196',
 'Var197',
 'Var198',
 'Var199',
 'Var200',
 'Var201',
 'Var202',
 'Var203',
 'Var204',
 'Var205',
 'Var206',
 'Var207',
 'Var208',
 'Var210',
 'Var211',
 'Var212',
 'Var213',
 'Var214',
 'Var215',
 'Var216',
 'Var217',
 'Var218',
 'Var219',
 'Var220',
 'Var221',
 'Var222',
 'Var223',
 'Var224',
 'Var225',
 'Var226',
 'Var227',
 'Var228',
 'Var229']

In [4]:
df[cat_cols].head()

,Var191,Var192,Var193,Var194,Var195,Var196,Var197,Var198,Var199,Var200,...,Var220,Var221,Var222,Var223,Var224,Var225,Var226,Var227,Var228,Var229
0,NaN,KXMrEyXXnK,g62hiBSaKg,SEuy,taul,1K8T,IvdZ,fhk21Ss,Pkku4gO,pbHkKHa,...,4UxGlow,zCkv,catzS2D,jySVZNlOJy,NaN,xG3x,Aoh3,ZI9m,ib5G6X1eUxUn6,mj86
1,NaN,8Knvyx875g,2Knk1KF,SEuy,taul,1K8T,lK27,eQgnKxT,Hz673939hbJdw,ELe4G18,...,GpvRJ5l,oslk,i06ocsg,LM8l689qOp,NaN,kG3k,WqMG,RAYp,55YFVY9,mj86
2,NaN,MfKrEyQtC3,RO12,SEuy,taul,1K8T,487l,iJzviRg,76j2P_OLn0,pOtdZA9,...,ch2oGfM,zCkv,P6pu4Vl,LM8l689qOp,NaN,kG3k,Aoh3,ZI9m,R4y5gQQWY8OodqDV,am7c
3,NaN,Qu0qrQKzJV,RO12,NaN,taul,1K8T,487l,3cunsla,ZIX6Y9cVy5,NaN,...,kH5mFX7,oslk,BNrD3Yd,LM8l689qOp,NaN,NaN,FSa2,RAYp,F2FyR07IdsN7I,NaN
4,NaN,DHerjIKQ76,RO12,NaN,taul,1K8T,YPhp,65ylkJq,glRbITbnHQ,NaN,...,x_lYlW4,oslk,3B1QowC,LM8l689qOp,NaN,NaN,WqMG,RAYp,F2FyR07IdsN7I,NaN

In [5]:
df[num_cols].head()

,Var1,Var2,Var3,Var4,Var5,Var6,Var7,Var8,Var9,Var10,...,Var184,Var185,Var186,Var187,Var188,Var189,Var190,Var209,Var230,y
0,NaN,NaN,NaN,NaN,NaN,812.0,14.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,NaN,NaN,NaN,NaN,NaN,2688.0,7.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,258.0,NaN,NaN,NaN,0
2,NaN,NaN,NaN,NaN,NaN,1015.0,14.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,288.0,NaN,NaN,NaN,0
3,NaN,NaN,NaN,NaN,NaN,168.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,NaN,NaN,NaN,NaN,NaN,14.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,186.0,NaN,NaN,NaN,0

In [6]:
from home_works.machine_learning.final_project.util import get_nan_percentage

allowed_columns = df.loc[:, get_nan_percentage(df) < 45].columns.tolist()

df_cleaned = df[allowed_columns]
df_cleaned.head()

,Var6,Var7,Var13,Var21,Var22,Var24,Var25,Var28,Var35,Var38,...,Var218,Var219,Var220,Var221,Var222,Var223,Var226,Var227,Var228,y
0,812.0,14.0,1252.0,156.0,195.0,0.0,40.0,286.96,0.0,4850466.0,...,cJvF,AU8_WTd,4UxGlow,zCkv,catzS2D,jySVZNlOJy,Aoh3,ZI9m,ib5G6X1eUxUn6,0
1,2688.0,7.0,8820.0,364.0,455.0,4.0,288.0,200.00,0.0,132072.0,...,UYBR,AU8pNoi,GpvRJ5l,oslk,i06ocsg,LM8l689qOp,WqMG,RAYp,55YFVY9,0
2,1015.0,14.0,1784.0,136.0,170.0,2.0,40.0,294.48,0.0,3223524.0,...,cJvF,FzaX,ch2oGfM,zCkv,P6pu4Vl,LM8l689qOp,Aoh3,ZI9m,R4y5gQQWY8OodqDV,0
3,168.0,0.0,0.0,24.0,30.0,0.0,0.0,644.24,0.0,2135430.0,...,cJvF,FzaX,kH5mFX7,oslk,BNrD3Yd,LM8l689qOp,FSa2,RAYp,F2FyR07IdsN7I,0
4,14.0,0.0,0.0,36.0,45.0,0.0,0.0,239.84,0.0,3110400.0,...,cJvF,FzaX,x_lYlW4,oslk,3B1QowC,LM8l689qOp,WqMG,RAYp,F2FyR07IdsN7I,0

In [7]:
from home_works.machine_learning.final_project.util import split_df_to_x_y

X, y = split_df_to_x_y(df_cleaned, "y")

In [8]:
from sklearn.pipeline import Pipeline
from home_works.machine_learning.final_project.util import VarMeanEstimator
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

original_num_cols = num_cols
num_cols = [c for c in num_cols if c in X.columns]

num_data_prep = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
    ("var_mean", VarMeanEstimator(col_name="VarMean", cols_to_mean=num_cols))
])

num_data_prep.set_output(transform="pandas")

num_data_scaled = num_data_prep.fit_transform(X[num_cols])

num_data_scaled.head()

,Var6,Var7,Var13,Var21,Var22,Var24,Var25,Var28,Var35,Var38,...,Var140,Var143,Var144,Var149,Var153,Var160,Var163,Var173,Var181,VarMean
0,-0.212337,1.192359,0.017317,-0.142524,-0.140019,-0.488119,-0.263571,0.641706,-0.228852,0.817387,...,-0.291121,-0.085463,1.354143,-0.389478,1.040498,-0.086067,-0.553093,-0.046956,-0.225677,0.238947
1,0.617608,0.020968,2.832081,0.253591,0.255808,-0.024392,0.943577,-0.252876,-0.228852,-0.804485,...,-0.408379,-0.085463,-0.223836,0.216229,-0.984923,-0.198993,0.063617,-0.046956,-0.225677,0.081564
2,-0.122530,1.192359,0.215183,-0.180612,-0.178080,-0.256256,-0.263571,0.719067,-0.228852,0.258152,...,1.487849,-0.085463,1.354143,0.454210,1.007088,-0.131238,0.611261,-0.046956,-0.225677,0.228111
3,-0.497243,-1.150423,-0.448339,-0.393904,-0.391218,-0.488119,-0.458272,4.317150,-0.228852,-0.115863,...,-0.428480,-0.085463,-0.223836,-0.389478,1.202683,-0.379674,-0.553093,-0.046956,-0.225677,0.028790
4,-0.565373,-1.150423,-0.448339,-0.371052,-0.368381,-0.488119,-0.458272,0.156969,-0.228852,0.219268,...,-0.428480,-0.085463,-1.012826,-0.389478,-0.840864,-0.402259,-0.553093,-0.046956,-0.225677,-0.383421

In [9]:
from home_works.machine_learning.final_project.util import CategoryHasher

original_cat_cols = cat_cols
cat_cols = [c for c in original_cat_cols if c in X.columns]

cat_prep = Pipeline(
    steps=[
        ("target_encoder", TargetEncoder(cols=cat_cols)),
        ("cat_hasher", CategoryHasher(col_name="CatHash", cat_cols=cat_cols))
    ]
)

cat_prep.set_output(transform="pandas")

cat_preped = cat_prep.fit_transform(X[cat_cols], y)

cat_preped.head()

,Var192,Var193,Var195,Var196,Var197,Var198,Var199,Var202,Var203,Var204,...,Var218,Var219,Var220,Var221,Var222,Var223,Var226,Var227,Var228,CatHash
0,0.125146,0.000001,0.134499,0.130097,0.103166,0.001046,0.220072,0.161831,0.129382,0.103960,...,0.103809,0.042021,0.001046,0.046923,0.001046,0.103865,0.107422,0.010355,0.001764,895916925
1,0.050972,0.000635,0.134499,0.130097,0.125277,0.100292,0.200129,0.167548,0.129382,0.148148,...,0.152126,0.086294,0.100292,0.167083,0.100292,0.130565,0.138601,0.175847,0.000000,3452461474
2,0.111988,0.179612,0.134499,0.130097,0.133047,0.016216,0.103704,0.137654,0.129382,0.103960,...,0.103809,0.131214,0.016216,0.046923,0.016216,0.130565,0.107422,0.010355,0.042614,851742526
3,0.147775,0.179612,0.134499,0.130097,0.133047,0.208904,0.197888,0.179664,0.129382,0.162896,...,0.103809,0.131214,0.208904,0.167083,0.208904,0.130565,0.177008,0.175847,0.193027,397410309
4,0.054165,0.179612,0.134499,0.130097,0.140250,0.102551,0.209801,0.111988,0.129382,0.123711,...,0.103809,0.131214,0.102551,0.167083,0.102551,0.130565,0.138601,0.175847,0.193027,2115856983

In [10]:
from home_works.machine_learning.final_project.util import concat_dfs

X_final = concat_dfs(num_data_scaled, cat_preped)
X_final.head()

,Var6,Var7,Var13,Var21,Var22,Var24,Var25,Var28,Var35,Var38,...,Var218,Var219,Var220,Var221,Var222,Var223,Var226,Var227,Var228,CatHash
0,-0.212337,1.192359,0.017317,-0.142524,-0.140019,-0.488119,-0.263571,0.641706,-0.228852,0.817387,...,0.103809,0.042021,0.001046,0.046923,0.001046,0.103865,0.107422,0.010355,0.001764,895916925
1,0.617608,0.020968,2.832081,0.253591,0.255808,-0.024392,0.943577,-0.252876,-0.228852,-0.804485,...,0.152126,0.086294,0.100292,0.167083,0.100292,0.130565,0.138601,0.175847,0.000000,3452461474
2,-0.122530,1.192359,0.215183,-0.180612,-0.178080,-0.256256,-0.263571,0.719067,-0.228852,0.258152,...,0.103809,0.131214,0.016216,0.046923,0.016216,0.130565,0.107422,0.010355,0.042614,851742526
3,-0.497243,-1.150423,-0.448339,-0.393904,-0.391218,-0.488119,-0.458272,4.317150,-0.228852,-0.115863,...,0.103809,0.131214,0.208904,0.167083,0.208904,0.130565,0.177008,0.175847,0.193027,397410309
4,-0.565373,-1.150423,-0.448339,-0.371052,-0.368381,-0.488119,-0.458272,0.156969,-0.228852,0.219268,...,0.103809,0.131214,0.102551,0.167083,0.102551,0.130565,0.138601,0.175847,0.193027,2115856983

In [11]:
from home_works.machine_learning.final_project.util import HyperParametersOptimizer

best_params = HyperParametersOptimizer(X_final, y).get_xgb_best_params(n_trials=100)

best_params

[I 2025-11-24 21:43:50,376] A new study created in memory with name: no-name-8687f443-e180-4122-92a1-61862b66f6e6
[I 2025-11-24 21:43:57,445] Trial 0 finished with value: 0.9589891061057129 and parameters: {'max_depth': 9, 'learning_rate': 0.24073864605873466, 'subsample': 0.5434984464404284, 'colsample_bytree': 0.9075941151499037, 'n_estimators': 909, 'scale_pos_weight': 3.51129376781289}. Best is trial 0 with value: 0.9589891061057129.
[I 2025-11-24 21:44:04,118] Trial 1 finished with value: 0.9681453795165021 and parameters: {'max_depth': 4, 'learning_rate': 0.06800441686277159, 'subsample': 0.6229408843559849, 'colsample_bytree': 0.47212209043185294, 'n_estimators': 766, 'scale_pos_weight': 1.358887249800282}. Best is trial 1 with value: 0.9681453795165021.
[I 2025-11-24 21:44:11,941] Trial 2 finished with value: 0.9589590040962342 and parameters: {'max_depth': 11, 'learning_rate': 0.15043776893825533, 'subsample': 0.5181771052201035, 'colsample_bytree': 0.7540308873502657, 'n_estimators': 862, 'scale_pos_weight': 7.781186984163415}. Best is trial 1 with value: 0.9681453795165021.
[I 2025-11-24 21:44:18,124] Trial 3 finished with value: 0.9611766286100474 and parameters: {'max_depth': 9, 'learning_rate': 0.23306532683542083, 'subsample': 0.8506686578439282, 'colsample_bytree': 0.5368557248561612, 'n_estimators': 732, 'scale_pos_weight': 9.466134262179166}. Best is trial 1 with value: 0.9681453795165021.
[I 2025-11-24 21:44:29,290] Trial 4 finished with value: 0.9641362101055932 and parameters: {'max_depth': 6, 'learning_rate': 0.017991630494021207, 'subsample': 0.8236516663360789, 'colsample_bytree': 0.3833109752426417, 'n_estimators': 945, 'scale_pos_weight': 6.410916511388747}. Best is trial 1 with value: 0.9681453795165021.
[I 2025-11-24 21:44:32,745] Trial 5 finished with value: 0.9576392054802595 and parameters: {'max_depth': 12, 'learning_rate': 0.25954647667227565, 'subsample': 0.5473864962168635, 'colsample_bytree': 0.6111753796102289, 'n_estimators': 343, 'scale_pos_weight': 1.924679908969011}. Best is trial 1 with value: 0.9681453795165021.
[I 2025-11-24 21:44:42,644] Trial 6 finished with value: 0.9594814116717434 and parameters: {'max_depth': 9, 'learning_rate': 0.0703037897405013, 'subsample': 0.980134488969553, 'colsample_bytree': 0.8834933622331868, 'n_estimators': 870, 'scale_pos_weight': 4.190406438560436}. Best is trial 1 with value: 0.9681453795165021.
[I 2025-11-24 21:44:49,620] Trial 7 finished with value: 0.9596998737861304 and parameters: {'max_depth': 8, 'learning_rate': 0.030860277293387767, 'subsample': 0.5040423454898999, 'colsample_bytree': 0.38324440551332567, 'n_estimators': 466, 'scale_pos_weight': 9.02959563474277}. Best is trial 1 with value: 0.9681453795165021.
[I 2025-11-24 21:44:57,034] Trial 8 finished with value: 0.9634123175496306 and parameters: {'max_depth': 10, 'learning_rate': 0.07291135775959035, 'subsample': 0.7219281372450388, 'colsample_bytree': 0.4537577446889277, 'n_estimators': 573, 'scale_pos_weight': 1.8942544815614721}. Best is trial 1 with value: 0.9681453795165021.
[I 2025-11-24 21:45:00,070] Trial 9 finished with value: 0.9602841068929588 and parameters: {'max_depth': 7, 'learning_rate': 0.06980469419302157, 'subsample': 0.9969086497925963, 'colsample_bytree': 0.8864002720345827, 'n_estimators': 212, 'scale_pos_weight': 7.6405331151017055}. Best is trial 1 with value: 0.9681453795165021.
[I 2025-11-24 21:45:04,934] Trial 10 finished with value: 0.9260383815946807 and parameters: {'max_depth': 3, 'learning_rate': 0.010523749052401414, 'subsample': 0.65569428453647, 'colsample_bytree': 0.3008305235682409, 'n_estimators': 704, 'scale_pos_weight': 4.206807826189208}. Best is trial 1 with value: 0.9681453795165021.
[I 2025-11-24 21:45:14,724] Trial 11 finished with value: 0.9663879064164881 and parameters: {'max_depth': 5, 'learning_rate': 0.02482595283447179, 'subsample': 0.8354850041735528, 'colsample_bytree': 0.45062674182827367, 'n_estimators': 988, 'scale_pos_weight': 6.140130907111002}. Best is trial 1 with value: 0.9681453795165021.
[I 2025-11-24 21:45:20,691] Trial 12 finished with value: 0.9626660490208806 and parameters: {'max_depth': 4, 'learning_rate': 0.03296410024028297, 'subsample': 0.6505430592359921, 'colsample_bytree': 0.5376044649450031, 'n_estimators': 734, 'scale_pos_weight': 5.7277964557767955}. Best is trial 1 with value: 0.9681453795165021.
[I 2025-11-24 21:45:28,870] Trial 13 finished with value: 0.9656105913180042 and parameters: {'max_depth': 5, 'learning_rate': 0.04091325090616671, 'subsample': 0.8673135385800883, 'colsample_bytree': 0.6765590139368498, 'n_estimators': 815, 'scale_pos_weight': 3.0144331472977637}. Best is trial 1 with value: 0.9681453795165021.
[I 2025-11-24 21:45:32,900] Trial 14 finished with value: 0.966582588178885 and parameters: {'max_depth': 3, 'learning_rate': 0.1153809522537714, 'subsample': 0.760167029223377, 'colsample_bytree': 0.4868136243725646, 'n_estimators': 597, 'scale_pos_weight': 5.247923003175114}. Best is trial 1 with value: 0.9681453795165021.
[I 2025-11-24 21:45:36,764] Trial 15 finished with value: 0.9627154147030825 and parameters: {'max_depth': 3, 'learning_rate': 0.11530080314941195, 'subsample': 0.6414839271351512, 'colsample_bytree': 0.557752284974858, 'n_estimators': 572, 'scale_pos_weight': 1.0483098463012377}. Best is trial 1 with value: 0.9681453795165021.
[I 2025-11-24 21:45:40,510] Trial 16 finished with value: 0.9653024209886457 and parameters: {'max_depth': 4, 'learning_rate': 0.11892688652759577, 'subsample': 0.7273022781223671, 'colsample_bytree': 0.7228529703067204, 'n_estimators': 464, 'scale_pos_weight': 5.065089655131223}. Best is trial 1 with value: 0.9681453795165021.
[I 2025-11-24 21:45:46,759] Trial 17 finished with value: 0.9632064791526697 and parameters: {'max_depth': 6, 'learning_rate': 0.1495097535081319, 'subsample': 0.7746254686752647, 'colsample_bytree': 0.4697823982721363, 'n_estimators': 653, 'scale_pos_weight': 7.258867368625412}. Best is trial 1 with value: 0.9681453795165021.
[I 2025-11-24 21:45:50,232] Trial 18 finished with value: 0.965794932038866 and parameters: {'max_depth': 3, 'learning_rate': 0.09339054385009143, 'subsample': 0.6065435934967326, 'colsample_bytree': 0.3051866285682332, 'n_estimators': 507, 'scale_pos_weight': 3.02426660559818}. Best is trial 1 with value: 0.9681453795165021.
[I 2025-11-24 21:45:54,494] Trial 19 finished with value: 0.96701210523554 and parameters: {'max_depth': 5, 'learning_rate': 0.05033001449451427, 'subsample': 0.9297969171622555, 'colsample_bytree': 0.6427739370664437, 'n_estimators': 377, 'scale_pos_weight': 4.7351992444727555}. Best is trial 1 with value: 0.9681453795165021.
[I 2025-11-24 21:45:57,094] Trial 20 finished with value: 0.9619584175277172 and parameters: {'max_depth': 5, 'learning_rate': 0.049398536294077755, 'subsample': 0.9070088161129979, 'colsample_bytree': 0.6452365042485668, 'n_estimators': 250, 'scale_pos_weight': 1.3163947678577634}. Best is trial 1 with value: 0.9681453795165021.
[I 2025-11-24 21:45:59,845] Trial 21 finished with value: 0.9621819914077202 and parameters: {'max_depth': 4, 'learning_rate': 0.055442103940770336, 'subsample': 0.9308850292188287, 'colsample_bytree': 0.7821757291077792, 'n_estimators': 335, 'scale_pos_weight': 4.957572760486517}. Best is trial 1 with value: 0.9681453795165021.
[I 2025-11-24 21:46:04,498] Trial 22 finished with value: 0.9656721194408939 and parameters: {'max_depth': 6, 'learning_rate': 0.08849627818002391, 'subsample': 0.7686954680329882, 'colsample_bytree': 0.575831935688104, 'n_estimators': 385, 'scale_pos_weight': 4.235313462417811}. Best is trial 1 with value: 0.9681453795165021.
[I 2025-11-24 21:46:11,142] Trial 23 finished with value: 0.9681995069079743 and parameters: {'max_depth': 4, 'learning_rate': 0.050065755974350284, 'subsample': 0.6839186024170021, 'colsample_bytree': 0.4895457779725138, 'n_estimators': 793, 'scale_pos_weight': 6.759519798231038}. Best is trial 23 with value: 0.9681995069079743.
[I 2025-11-24 21:46:21,252] Trial 24 finished with value: 0.9640076168526501 and parameters: {'max_depth': 7, 'learning_rate': 0.0455547258161278, 'subsample': 0.6037496526021255, 'colsample_bytree': 0.4089501882926625, 'n_estimators': 827, 'scale_pos_weight': 8.504108344270684}. Best is trial 23 with value: 0.9681995069079743.
[I 2025-11-24 21:46:27,844] Trial 25 finished with value: 0.9580358390921383 and parameters: {'max_depth': 4, 'learning_rate': 0.020959167917027968, 'subsample': 0.6961691857314248, 'colsample_bytree': 0.8086393484405896, 'n_estimators': 783, 'scale_pos_weight': 6.769045102224755}. Best is trial 23 with value: 0.9681995069079743.
[I 2025-11-24 21:46:34,311] Trial 26 finished with value: 0.9616325661052272 and parameters: {'max_depth': 5, 'learning_rate': 0.03575244472583149, 'subsample': 0.5927233477369422, 'colsample_bytree': 0.647855879548846, 'n_estimators': 642, 'scale_pos_weight': 8.427715184142034}. Best is trial 23 with value: 0.9681995069079743.
[I 2025-11-24 21:46:41,784] Trial 27 finished with value: 0.9624570493689241 and parameters: {'max_depth': 6, 'learning_rate': 0.0574509886022112, 'subsample': 0.6854632858615995, 'colsample_bytree': 0.975946920550878, 'n_estimators': 685, 'scale_pos_weight': 2.2084629190804783}. Best is trial 23 with value: 0.9681995069079743.
[I 2025-11-24 21:46:48,394] Trial 28 finished with value: 0.9475271600236892 and parameters: {'max_depth': 4, 'learning_rate': 0.014797840384282637, 'subsample': 0.5713189436761117, 'colsample_bytree': 0.5114324259379444, 'n_estimators': 800, 'scale_pos_weight': 6.882298494380706}. Best is trial 23 with value: 0.9681995069079743.
[I 2025-11-24 21:46:58,640] Trial 29 finished with value: 0.9653528192449917 and parameters: {'max_depth': 8, 'learning_rate': 0.05827239526810969, 'subsample': 0.7983267008638743, 'colsample_bytree': 0.600047391336656, 'n_estimators': 898, 'scale_pos_weight': 9.974389939332386}. Best is trial 23 with value: 0.9681995069079743.
[I 2025-11-24 21:47:04,100] Trial 30 finished with value: 0.9639721462396539 and parameters: {'max_depth': 5, 'learning_rate': 0.02441348850038957, 'subsample': 0.8928380072264135, 'colsample_bytree': 0.6942869218178687, 'n_estimators': 515, 'scale_pos_weight': 3.423241032250116}. Best is trial 23 with value: 0.9681995069079743.
[I 2025-11-24 21:47:09,376] Trial 31 finished with value: 0.9658612067402427 and parameters: {'max_depth': 3, 'learning_rate': 0.08665352130454546, 'subsample': 0.7464065915242568, 'colsample_bytree': 0.48834613283339556, 'n_estimators': 757, 'scale_pos_weight': 5.475835948549732}. Best is trial 23 with value: 0.9681995069079743.
[I 2025-11-24 21:47:13,708] Trial 32 finished with value: 0.9657061805801004 and parameters: {'max_depth': 3, 'learning_rate': 0.20051837158261393, 'subsample': 0.9527013130699299, 'colsample_bytree': 0.4176063415605615, 'n_estimators': 618, 'scale_pos_weight': 4.735525908974274}. Best is trial 23 with value: 0.9681995069079743.
[I 2025-11-24 21:47:17,141] Trial 33 finished with value: 0.9654107628412685 and parameters: {'max_depth': 4, 'learning_rate': 0.13340196539959318, 'subsample': 0.6830461303334814, 'colsample_bytree': 0.35500726104710684, 'n_estimators': 412, 'scale_pos_weight': 5.81968199410063}. Best is trial 23 with value: 0.9681995069079743.
[I 2025-11-24 21:47:23,243] Trial 34 finished with value: 0.9579403637949246 and parameters: {'max_depth': 3, 'learning_rate': 0.20317952296972389, 'subsample': 0.6263665367781214, 'colsample_bytree': 0.5106144895685435, 'n_estimators': 931, 'scale_pos_weight': 2.6837105359324225}. Best is trial 23 with value: 0.9681995069079743.
[I 2025-11-24 21:47:29,974] Trial 35 finished with value: 0.9656260458552065 and parameters: {'max_depth': 4, 'learning_rate': 0.10112231677447349, 'subsample': 0.6713104493242172, 'colsample_bytree': 0.5933847752465712, 'n_estimators': 862, 'scale_pos_weight': 3.697001810245142}. Best is trial 23 with value: 0.9681995069079743.
[I 2025-11-24 21:47:32,820] Trial 36 finished with value: 0.957112647553761 and parameters: {'max_depth': 5, 'learning_rate': 0.07393257489387366, 'subsample': 0.5392205665075471, 'colsample_bytree': 0.35277103488643297, 'n_estimators': 269, 'scale_pos_weight': 6.344744407563234}. Best is trial 23 with value: 0.9681995069079743.
[I 2025-11-24 21:47:40,632] Trial 37 finished with value: 0.9636231047818619 and parameters: {'max_depth': 6, 'learning_rate': 0.040571802360300835, 'subsample': 0.7978648266768262, 'colsample_bytree': 0.5146054026332219, 'n_estimators': 682, 'scale_pos_weight': 8.072604884572405}. Best is trial 23 with value: 0.9681995069079743.
[I 2025-11-24 21:47:55,168] Trial 38 finished with value: 0.9609975350254043 and parameters: {'max_depth': 12, 'learning_rate': 0.02966833946570779, 'subsample': 0.7073137937618832, 'colsample_bytree': 0.4299048597838058, 'n_estimators': 571, 'scale_pos_weight': 7.136709222940899}. Best is trial 23 with value: 0.9681995069079743.
[I 2025-11-24 21:48:05,533] Trial 39 finished with value: 0.9635709934269177 and parameters: {'max_depth': 7, 'learning_rate': 0.06332136466737438, 'subsample': 0.577935604506962, 'colsample_bytree': 0.8262340794220657, 'n_estimators': 758, 'scale_pos_weight': 5.33244444100595}. Best is trial 23 with value: 0.9681995069079743.
[I 2025-11-24 21:48:15,876] Trial 40 finished with value: 0.966974695343836 and parameters: {'max_depth': 3, 'learning_rate': 0.08199671495704255, 'subsample': 0.8733974925389993, 'colsample_bytree': 0.6283438385659043, 'n_estimators': 998, 'scale_pos_weight': 4.570989832760169}. Best is trial 23 with value: 0.9681995069079743.
[I 2025-11-24 21:48:25,040] Trial 41 finished with value: 0.9688697549002885 and parameters: {'max_depth': 3, 'learning_rate': 0.0759539561311162, 'subsample': 0.8861940555753182, 'colsample_bytree': 0.6411364799411661, 'n_estimators': 983, 'scale_pos_weight': 3.8761902611781203}. Best is trial 41 with value: 0.9688697549002885.
[I 2025-11-24 21:48:33,687] Trial 42 finished with value: 0.9671967506628667 and parameters: {'max_depth': 4, 'learning_rate': 0.07656007595455451, 'subsample': 0.9559106726105856, 'colsample_bytree': 0.6346247403849516, 'n_estimators': 980, 'scale_pos_weight': 4.43908882735772}. Best is trial 41 with value: 0.9688697549002885.
[I 2025-11-24 21:48:43,459] Trial 43 finished with value: 0.9668869331732065 and parameters: {'max_depth': 4, 'learning_rate': 0.04925918578677075, 'subsample': 0.9588894652392145, 'colsample_bytree': 0.7293763513948884, 'n_estimators': 966, 'scale_pos_weight': 3.7378638847981596}. Best is trial 41 with value: 0.9688697549002885.
[I 2025-11-24 21:48:55,324] Trial 44 finished with value: 0.9666518876114252 and parameters: {'max_depth': 5, 'learning_rate': 0.06406563258626131, 'subsample': 0.9244026570960939, 'colsample_bytree': 0.6719442404842592, 'n_estimators': 920, 'scale_pos_weight': 2.4154949773446837}. Best is trial 41 with value: 0.9688697549002885.
[I 2025-11-24 21:49:04,760] Trial 45 finished with value: 0.9692490409432312 and parameters: {'max_depth': 4, 'learning_rate': 0.039700968796728325, 'subsample': 0.9965116471798217, 'colsample_bytree': 0.5655809473155758, 'n_estimators': 858, 'scale_pos_weight': 4.480147318751032}. Best is trial 45 with value: 0.9692490409432312.
[I 2025-11-24 21:49:18,429] Trial 46 finished with value: 0.9696252913972296 and parameters: {'max_depth': 4, 'learning_rate': 0.03867257789391383, 'subsample': 0.9999847309885114, 'colsample_bytree': 0.5707054326361998, 'n_estimators': 879, 'scale_pos_weight': 3.33536749602249}. Best is trial 46 with value: 0.9696252913972296.
[I 2025-11-24 21:49:36,094] Trial 47 finished with value: 0.9627962809022256 and parameters: {'max_depth': 10, 'learning_rate': 0.03987279843341567, 'subsample': 0.9966362130852989, 'colsample_bytree': 0.5557093039011387, 'n_estimators': 860, 'scale_pos_weight': 3.2986972496780878}. Best is trial 46 with value: 0.9696252913972296.
[I 2025-11-24 21:49:45,603] Trial 48 finished with value: 0.9689014245623845 and parameters: {'max_depth': 4, 'learning_rate': 0.02756457667522238, 'subsample': 0.9822163950540616, 'colsample_bytree': 0.5554889047540786, 'n_estimators': 894, 'scale_pos_weight': 3.972984415935381}. Best is trial 46 with value: 0.9696252913972296.
[I 2025-11-24 21:49:52,737] Trial 49 finished with value: 0.9649012360784358 and parameters: {'max_depth': 3, 'learning_rate': 0.02726547754863787, 'subsample': 0.9794007762997647, 'colsample_bytree': 0.574315192887751, 'n_estimators': 886, 'scale_pos_weight': 3.655330961839053}. Best is trial 46 with value: 0.9696252913972296.
[I 2025-11-24 21:50:07,436] Trial 50 finished with value: 0.9620517332299613 and parameters: {'max_depth': 4, 'learning_rate': 0.01613713358127931, 'subsample': 0.9697029563132559, 'colsample_bytree': 0.543842794139922, 'n_estimators': 838, 'scale_pos_weight': 4.009806039860166}. Best is trial 46 with value: 0.9696252913972296.
[I 2025-11-24 21:50:17,200] Trial 51 finished with value: 0.9721998885573273 and parameters: {'max_depth': 4, 'learning_rate': 0.03627472200041106, 'subsample': 0.9972161101334032, 'colsample_bytree': 0.4820215554558748, 'n_estimators': 918, 'scale_pos_weight': 2.9477677091728873}. Best is trial 51 with value: 0.9721998885573273.
[I 2025-11-24 21:50:25,675] Trial 52 finished with value: 0.9695782775809432 and parameters: {'max_depth': 4, 'learning_rate': 0.03607355383054644, 'subsample': 0.9985929539465097, 'colsample_bytree': 0.607495987655881, 'n_estimators': 947, 'scale_pos_weight': 3.056237026562397}. Best is trial 51 with value: 0.9721998885573273.
[I 2025-11-24 21:50:31,855] Trial 53 finished with value: 0.9630659441205995 and parameters: {'max_depth': 3, 'learning_rate': 0.021054500725284905, 'subsample': 0.9985053932326011, 'colsample_bytree': 0.6127607738678005, 'n_estimators': 923, 'scale_pos_weight': 2.837005094392192}. Best is trial 51 with value: 0.9721998885573273.
[I 2025-11-24 21:50:42,465] Trial 54 finished with value: 0.9672006638926776 and parameters: {'max_depth': 5, 'learning_rate': 0.03394961453703176, 'subsample': 0.9373305157300232, 'colsample_bytree': 0.6834808091174, 'n_estimators': 950, 'scale_pos_weight': 3.1573707333942345}. Best is trial 51 with value: 0.9721998885573273.
[I 2025-11-24 21:50:56,844] Trial 55 finished with value: 0.9618706980930195 and parameters: {'max_depth': 11, 'learning_rate': 0.03661366567628242, 'subsample': 0.9798819398468839, 'colsample_bytree': 0.5820089973981298, 'n_estimators': 957, 'scale_pos_weight': 1.8768385035692847}. Best is trial 51 with value: 0.9721998885573273.
[I 2025-11-24 21:51:05,448] Trial 56 finished with value: 0.9710906105388863 and parameters: {'max_depth': 4, 'learning_rate': 0.02910231656019566, 'subsample': 0.9121817105197803, 'colsample_bytree': 0.5286073318540182, 'n_estimators': 900, 'scale_pos_weight': 2.4266327376636827}. Best is trial 51 with value: 0.9721998885573273.
[I 2025-11-24 21:51:18,691] Trial 57 finished with value: 0.9655297701130282 and parameters: {'max_depth': 6, 'learning_rate': 0.02396318005446277, 'subsample': 0.9081120169178533, 'colsample_bytree': 0.5301857075916995, 'n_estimators': 892, 'scale_pos_weight': 1.836450726498033}. Best is trial 51 with value: 0.9721998885573273.
[I 2025-11-24 21:51:27,406] Trial 58 finished with value: 0.9714625703827224 and parameters: {'max_depth': 4, 'learning_rate': 0.031680912839639905, 'subsample': 0.9992940369297785, 'colsample_bytree': 0.4605329565445222, 'n_estimators': 843, 'scale_pos_weight': 2.6463956082237847}. Best is trial 51 with value: 0.9721998885573273.
[I 2025-11-24 21:51:36,650] Trial 59 finished with value: 0.9694898267055796 and parameters: {'max_depth': 5, 'learning_rate': 0.03187098784938566, 'subsample': 0.9509514209813216, 'colsample_bytree': 0.4474042643387531, 'n_estimators': 844, 'scale_pos_weight': 2.447178055049158}. Best is trial 51 with value: 0.9721998885573273.

{'max_depth': 3,
 'learning_rate': 0.051641128892375265,
 'subsample': 0.9836035761611458,
 'colsample_bytree': 0.34474575431527066,
 'n_estimators': 851,
 'scale_pos_weight': 2.309453619314037}

In [12]:
from xgboost import XGBClassifier

model = XGBClassifier(**best_params)

In [13]:
from home_works.machine_learning.final_project.util import evaluate_model_avg_accuracy

evaluate_model_avg_accuracy(model, X_final, y)

Точність для кожного фолду: [0.9895 0.9935 0.991  0.9895 0.994 ]
Середня точність: 0.9915

In [14]:
from home_works.machine_learning.final_project.util import evaluate_model, split_train_test

X_train, X_test, y_train, y_test = split_train_test(X_final, y)
evaluate_model(model, X_train, y_train, X_test, y_test)

Звіт для порогу 0.4:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1737
           1       0.98      0.98      0.98       263

    accuracy                           0.99      2000
   macro avg       0.99      0.99      0.99      2000
weighted avg       1.00      0.99      1.00      2000

In [15]:
from imblearn.over_sampling import SMOTE

final_model = XGBClassifier(**best_params)

sm = SMOTE(random_state=42)
X_res, y_res = sm.fit_resample(X_final, y)

final_model.fit(X_res, y_res)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.34474575431527066, device=None,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, feature_types=None, feature_weights=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.051641128892375265,
              max_bin=None, max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=851, n_jobs=None,
              num_parallel_tree=None, ...)

In [16]:
validation_data = read_csv("ml-fundamentals-and-applications-2025-10/final_proj_test.csv")

validation_data.head()

,Var1,Var2,Var3,Var4,Var5,Var6,Var7,Var8,Var9,Var10,...,Var221,Var222,Var223,Var224,Var225,Var226,Var227,Var228,Var229,Var230
0,NaN,NaN,NaN,NaN,NaN,819.0,7.0,NaN,NaN,NaN,...,zCkv,catzS2D,LM8l689qOp,NaN,ELof,rgKb,ZI9m,ib5G6X1eUxUn6,am7c,NaN
1,NaN,NaN,NaN,NaN,NaN,3192.0,28.0,NaN,NaN,NaN,...,oslk,QkgQQMs,LM8l689qOp,NaN,NaN,453m,RAYp,F2FyR07IdsN7I,am7c,NaN
2,NaN,NaN,NaN,NaN,NaN,756.0,0.0,NaN,NaN,NaN,...,oslk,bxCQb98,jySVZNlOJy,NaN,NaN,Qu4f,RAYp,F2FyR07IdsN7I,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,3892.0,21.0,NaN,NaN,NaN,...,oslk,0JeRt72,M_8D,NaN,ELof,Aoh3,RAYp,F2FyR07IdsN7I,mj86,NaN
4,NaN,NaN,NaN,NaN,NaN,672.0,7.0,NaN,NaN,NaN,...,oslk,0p8OTZB,LM8l689qOp,NaN,ELof,xb3V,RAYp,F2FyR07IdsN7I,mj86,NaN

In [17]:
allowed_columns.remove("y")
df_cleaned_final = validation_data[allowed_columns]
df_cleaned_final.head()

,Var6,Var7,Var13,Var21,Var22,Var24,Var25,Var28,Var35,Var38,...,Var217,Var218,Var219,Var220,Var221,Var222,Var223,Var226,Var227,Var228
0,819.0,7.0,0.0,160.0,200.0,2.0,56.0,403.36,0.0,4800036.0,...,6ITF,cJvF,FzaX,4UxGlow,zCkv,catzS2D,LM8l689qOp,rgKb,ZI9m,ib5G6X1eUxUn6
1,3192.0,28.0,3864.0,380.0,475.0,8.0,288.0,200.00,0.0,51282.0,...,RRN_,UYBR,FzaX,k5O88FJ,oslk,QkgQQMs,LM8l689qOp,453m,RAYp,F2FyR07IdsN7I
2,756.0,0.0,0.0,156.0,195.0,2.0,40.0,402.24,0.0,3462336.0,...,c4pP,UYBR,FzaX,h72uX8Z,oslk,bxCQb98,jySVZNlOJy,Qu4f,RAYp,F2FyR07IdsN7I
3,3892.0,21.0,5192.0,152.0,190.0,0.0,8.0,212.08,0.0,7331880.0,...,fgNW,UYBR,FzaX,VA_88FJ,oslk,0JeRt72,M_8D,Aoh3,RAYp,F2FyR07IdsN7I
4,672.0,7.0,16.0,144.0,180.0,2.0,64.0,322.64,0.0,381480.0,...,dvCm,UYBR,FzaX,FB4YlW4,oslk,0p8OTZB,LM8l689qOp,xb3V,RAYp,F2FyR07IdsN7I

In [18]:
num_cols_final = df_cleaned_final.select_dtypes(include=["number"]).columns.tolist()

df_cleaned_final[num_cols_final].head()

,Var6,Var7,Var13,Var21,Var22,Var24,Var25,Var28,Var35,Var38,...,Var134,Var140,Var143,Var144,Var149,Var153,Var160,Var163,Var173,Var181
0,819.0,7.0,0.0,160.0,200.0,2.0,56.0,403.36,0.0,4800036.0,...,807760.0,20.0,0.0,18.0,554435.0,10948360.0,22.0,0.0,0.0,0.0
1,3192.0,28.0,3864.0,380.0,475.0,8.0,288.0,200.00,0.0,51282.0,...,327752.0,1835.0,0.0,9.0,280392.0,2101956.0,46.0,375756.0,0.0,0.0
2,756.0,0.0,0.0,156.0,195.0,2.0,40.0,402.24,0.0,3462336.0,...,796264.0,0.0,0.0,9.0,554400.0,10325800.0,26.0,475200.0,0.0,0.0
3,3892.0,21.0,5192.0,152.0,190.0,0.0,8.0,212.08,0.0,7331880.0,...,13754.0,2905.0,0.0,0.0,0.0,10596480.0,18.0,0.0,0.0,0.0
4,672.0,7.0,16.0,144.0,180.0,2.0,64.0,322.64,0.0,381480.0,...,104290.0,430.0,0.0,27.0,46963.0,2004852.0,42.0,40254.0,0.0,7.0

In [19]:
cat_cols_final = df_cleaned_final.drop(columns=num_cols_final).columns.tolist()
df_cleaned_final[cat_cols_final].head()

,Var192,Var193,Var195,Var196,Var197,Var198,Var199,Var202,Var203,Var204,...,Var217,Var218,Var219,Var220,Var221,Var222,Var223,Var226,Var227,Var228
0,75lTmBtFkL,rEUOq2QD1qfkRr6qpua,taul,1K8T,F9g8,fhk21Ss,GVWDufEPyV,GHne,9_Y1,c2JP,...,6ITF,cJvF,FzaX,4UxGlow,zCkv,catzS2D,LM8l689qOp,rgKb,ZI9m,ib5G6X1eUxUn6
1,1YVgUHXZeb,RO12,taul,1K8T,0Xwj,Ml6kiFp,S85OeCBjSz,14hG,HLqf,8BBI,...,RRN_,UYBR,FzaX,k5O88FJ,oslk,QkgQQMs,LM8l689qOp,453m,RAYp,F2FyR07IdsN7I
2,cFHt0GoOh3,RO12,taul,1K8T,wGW5,Wq69B7S,z7GH4Up,dK_l,9_Y1,rGJy,...,c4pP,UYBR,FzaX,h72uX8Z,oslk,bxCQb98,jySVZNlOJy,Qu4f,RAYp,F2FyR07IdsN7I
3,m9SrEy7Rm6,RO12,taul,1K8T,JLbT,4JEMGuV,oQ173939hSRjL,zqqA,9_Y1,X8zP,...,fgNW,UYBR,FzaX,VA_88FJ,oslk,0JeRt72,M_8D,Aoh3,RAYp,F2FyR07IdsN7I
4,BQavyxLp3Z,RO12,taul,1K8T,lK27,32pCIek,JQFeOYK,YqMO,9_Y1,_r21,...,dvCm,UYBR,FzaX,FB4YlW4,oslk,0p8OTZB,LM8l689qOp,xb3V,RAYp,F2FyR07IdsN7I

In [20]:
# Використовуємо .transform(), а не .fit_transform().
# Пайплайни вже "навчені" на X та y вище. Тепер ми просто застосовуємо знання до нових даних.

# 1. Числові дані: Тільки transform
num_data_scaled_final = num_data_prep.transform(df_cleaned_final[num_cols_final])
num_data_scaled_final.head()

/Users/kozak_mamay/PycharmProjects/WoolfDataScience/.venv/lib/python3.12/site-packages/sklearn/pipeline.py:61: FutureWarning: This Pipeline instance is not fitted yet. Call 'fit' with appropriate arguments before using other methods such as transform, predict, etc. This will raise an error in 1.8 instead of the current warning.
  warnings.warn(

,Var6,Var7,Var13,Var21,Var22,Var24,Var25,Var28,Var35,Var38,...,Var140,Var143,Var144,Var149,Var153,Var160,Var163,Var173,Var181,VarMean
0,-0.209240,0.020968,-0.448339,-0.134906,-0.132407,-0.256256,-0.185691,1.839147,-0.228852,0.800053,...,-0.421779,-0.085463,0.565153,0.454232,1.103946,-0.176408,-0.553093,-0.046956,-0.225677,0.088950
1,0.840578,3.535141,0.988797,0.284062,0.286256,0.439335,0.943577,-0.252876,-0.228852,-0.832255,...,0.186286,-0.085463,-0.223836,0.037207,-1.015704,0.094614,-0.092764,-0.046956,-0.225677,0.336799
2,-0.237111,-1.150423,-0.448339,-0.142524,-0.140019,-0.256256,-0.263571,1.827625,-0.228852,0.340240,...,-0.428480,-0.085463,-0.223836,0.454178,0.954777,-0.131238,0.029062,-0.046956,-0.225677,-0.070584
3,1.150259,2.363750,1.482720,-0.150141,-0.147631,-0.488119,-0.419332,-0.128606,-0.228852,1.670334,...,0.544761,-0.085463,-1.012826,-0.389478,1.019633,-0.221578,-0.553093,-0.046956,-0.225677,0.237190
4,-0.274273,0.020968,-0.442389,-0.165377,-0.162856,-0.256256,-0.146750,1.008757,-0.228852,-0.718755,...,-0.284420,-0.085463,1.354143,-0.318013,-1.038970,0.049443,-0.503779,-0.046956,2.739857,-0.030746

In [21]:
# 2. Категоріальні дані: Тільки transform (y тут не потрібен)
# Також передаємо df_cleaned_final[cat_cols_final], а не просто список назв
cat_preped_final = cat_prep.transform(df_cleaned_final[cat_cols_final])

cat_preped_final.head()

/Users/kozak_mamay/PycharmProjects/WoolfDataScience/.venv/lib/python3.12/site-packages/sklearn/pipeline.py:61: FutureWarning: This Pipeline instance is not fitted yet. Call 'fit' with appropriate arguments before using other methods such as transform, predict, etc. This will raise an error in 1.8 instead of the current warning.
  warnings.warn(

,Var192,Var193,Var195,Var196,Var197,Var198,Var199,Var202,Var203,Var204,...,Var218,Var219,Var220,Var221,Var222,Var223,Var226,Var227,Var228,CatHash
0,0.186809,0.000065,0.134499,0.130097,0.221757,0.001046,0.083739,0.130500,0.129382,0.153590,...,0.103809,0.131214,0.001046,0.046923,0.001046,0.130565,0.154122,0.010355,0.001764,4062825425
1,0.168718,0.179612,0.134499,0.130097,0.143165,0.146781,0.139026,0.182914,0.118976,0.132338,...,0.152126,0.131214,0.146781,0.167083,0.146781,0.130565,0.139810,0.175847,0.193027,1061715435
2,0.134454,0.179612,0.134499,0.130097,0.081382,0.182914,0.111988,0.106693,0.129382,0.148936,...,0.152126,0.131214,0.182914,0.167083,0.182914,0.103865,0.102140,0.175847,0.193027,3074153173
3,0.102266,0.179612,0.134499,0.130097,0.113208,0.171611,0.111988,0.110342,0.129382,0.138211,...,0.152126,0.131214,0.171611,0.167083,0.171611,0.089059,0.107422,0.175847,0.193027,373545982
4,0.141625,0.179612,0.134499,0.130097,0.125277,0.208904,0.049495,0.182914,0.129382,0.097272,...,0.152126,0.131214,0.208904,0.167083,0.208904,0.130565,0.126829,0.175847,0.193027,3147801759

In [22]:
num_preped_final = num_data_prep.transform(df_cleaned_final[num_cols_final])
num_preped_final.head()

/Users/kozak_mamay/PycharmProjects/WoolfDataScience/.venv/lib/python3.12/site-packages/sklearn/pipeline.py:61: FutureWarning: This Pipeline instance is not fitted yet. Call 'fit' with appropriate arguments before using other methods such as transform, predict, etc. This will raise an error in 1.8 instead of the current warning.
  warnings.warn(

,Var6,Var7,Var13,Var21,Var22,Var24,Var25,Var28,Var35,Var38,...,Var140,Var143,Var144,Var149,Var153,Var160,Var163,Var173,Var181,VarMean
0,-0.209240,0.020968,-0.448339,-0.134906,-0.132407,-0.256256,-0.185691,1.839147,-0.228852,0.800053,...,-0.421779,-0.085463,0.565153,0.454232,1.103946,-0.176408,-0.553093,-0.046956,-0.225677,0.088950
1,0.840578,3.535141,0.988797,0.284062,0.286256,0.439335,0.943577,-0.252876,-0.228852,-0.832255,...,0.186286,-0.085463,-0.223836,0.037207,-1.015704,0.094614,-0.092764,-0.046956,-0.225677,0.336799
2,-0.237111,-1.150423,-0.448339,-0.142524,-0.140019,-0.256256,-0.263571,1.827625,-0.228852,0.340240,...,-0.428480,-0.085463,-0.223836,0.454178,0.954777,-0.131238,0.029062,-0.046956,-0.225677,-0.070584
3,1.150259,2.363750,1.482720,-0.150141,-0.147631,-0.488119,-0.419332,-0.128606,-0.228852,1.670334,...,0.544761,-0.085463,-1.012826,-0.389478,1.019633,-0.221578,-0.553093,-0.046956,-0.225677,0.237190
4,-0.274273,0.020968,-0.442389,-0.165377,-0.162856,-0.256256,-0.146750,1.008757,-0.228852,-0.718755,...,-0.284420,-0.085463,1.354143,-0.318013,-1.038970,0.049443,-0.503779,-0.046956,2.739857,-0.030746

In [23]:
df_final = concat_dfs(cat_preped_final, num_preped_final)

df_final.head()

,Var192,Var193,Var195,Var196,Var197,Var198,Var199,Var202,Var203,Var204,...,Var140,Var143,Var144,Var149,Var153,Var160,Var163,Var173,Var181,VarMean
0,0.186809,0.000065,0.134499,0.130097,0.221757,0.001046,0.083739,0.130500,0.129382,0.153590,...,-0.421779,-0.085463,0.565153,0.454232,1.103946,-0.176408,-0.553093,-0.046956,-0.225677,0.088950
1,0.168718,0.179612,0.134499,0.130097,0.143165,0.146781,0.139026,0.182914,0.118976,0.132338,...,0.186286,-0.085463,-0.223836,0.037207,-1.015704,0.094614,-0.092764,-0.046956,-0.225677,0.336799
2,0.134454,0.179612,0.134499,0.130097,0.081382,0.182914,0.111988,0.106693,0.129382,0.148936,...,-0.428480,-0.085463,-0.223836,0.454178,0.954777,-0.131238,0.029062,-0.046956,-0.225677,-0.070584
3,0.102266,0.179612,0.134499,0.130097,0.113208,0.171611,0.111988,0.110342,0.129382,0.138211,...,0.544761,-0.085463,-1.012826,-0.389478,1.019633,-0.221578,-0.553093,-0.046956,-0.225677,0.237190
4,0.141625,0.179612,0.134499,0.130097,0.125277,0.208904,0.049495,0.182914,0.129382,0.097272,...,-0.284420,-0.085463,1.354143,-0.318013,-1.038970,0.049443,-0.503779,-0.046956,2.739857,-0.030746

In [24]:
# Отримуємо правильний порядок ознак безпосередньо з навченої моделі (booster)
cols_when_model_builds = final_model.get_booster().feature_names

# Перевпорядковуємо df_final, щоб стовпці йшли у точній послідовності, яку очікує модель
# Це також автоматично відфільтрує зайві стовпці, якщо такі є
df_final = df_final[cols_when_model_builds]

# Тепер виконуємо передбачення без помилок
prediction_final = final_model.predict(df_final)

In [25]:
from home_works.machine_learning.final_project.util import write_submission_csv

write_submission_csv(prediction_final, "final_submission_xgb.csv")