In [1]:
from category_encoders import TargetEncoder
from pandas import read_csv

df = read_csv("ml-fundamentals-and-applications-2025-10/final_proj_data.csv")
df.head()

,Var1,Var2,Var3,Var4,Var5,Var6,Var7,Var8,Var9,Var10,...,Var222,Var223,Var224,Var225,Var226,Var227,Var228,Var229,Var230,y
0,NaN,NaN,NaN,NaN,NaN,812.0,14.0,NaN,NaN,NaN,...,catzS2D,jySVZNlOJy,NaN,xG3x,Aoh3,ZI9m,ib5G6X1eUxUn6,mj86,NaN,0
1,NaN,NaN,NaN,NaN,NaN,2688.0,7.0,NaN,NaN,NaN,...,i06ocsg,LM8l689qOp,NaN,kG3k,WqMG,RAYp,55YFVY9,mj86,NaN,0
2,NaN,NaN,NaN,NaN,NaN,1015.0,14.0,NaN,NaN,NaN,...,P6pu4Vl,LM8l689qOp,NaN,kG3k,Aoh3,ZI9m,R4y5gQQWY8OodqDV,am7c,NaN,0
3,NaN,NaN,NaN,NaN,NaN,168.0,0.0,NaN,NaN,NaN,...,BNrD3Yd,LM8l689qOp,NaN,NaN,FSa2,RAYp,F2FyR07IdsN7I,NaN,NaN,0
4,NaN,NaN,NaN,NaN,NaN,14.0,0.0,NaN,NaN,NaN,...,3B1QowC,LM8l689qOp,NaN,NaN,WqMG,RAYp,F2FyR07IdsN7I,NaN,NaN,0

In [2]:
num_cols = df.select_dtypes(include=["number"]).columns.tolist()
num_cols

['Var1',
 'Var2',
 'Var3',
 'Var4',
 'Var5',
 'Var6',
 'Var7',
 'Var8',
 'Var9',
 'Var10',
 'Var11',
 'Var12',
 'Var13',
 'Var14',
 'Var15',
 'Var16',
 'Var17',
 'Var18',
 'Var19',
 'Var20',
 'Var21',
 'Var22',
 'Var23',
 'Var24',
 'Var25',
 'Var26',
 'Var27',
 'Var28',
 'Var29',
 'Var30',
 'Var31',
 'Var32',
 'Var33',
 'Var34',
 'Var35',
 'Var36',
 'Var37',
 'Var38',
 'Var39',
 'Var40',
 'Var41',
 'Var42',
 'Var43',
 'Var44',
 'Var45',
 'Var46',
 'Var47',
 'Var48',
 'Var49',
 'Var50',
 'Var51',
 'Var52',
 'Var53',
 'Var54',
 'Var55',
 'Var56',
 'Var57',
 'Var58',
 'Var59',
 'Var60',
 'Var61',
 'Var62',
 'Var63',
 'Var64',
 'Var65',
 'Var66',
 'Var67',
 'Var68',
 'Var69',
 'Var70',
 'Var71',
 'Var72',
 'Var73',
 'Var74',
 'Var75',
 'Var76',
 'Var77',
 'Var78',
 'Var79',
 'Var80',
 'Var81',
 'Var82',
 'Var83',
 'Var84',
 'Var85',
 'Var86',
 'Var87',
 'Var88',
 'Var89',
 'Var90',
 'Var91',
 'Var92',
 'Var93',
 'Var94',
 'Var95',
 'Var96',
 'Var97',
 'Var98',
 'Var99',
 'Var100',
 'Var101',
 'Var102',
 'Var103',
 'Var104',
 'Var105',
 'Var106',
 'Var107',
 'Var108',
 'Var109',
 'Var110',
 'Var111',
 'Var112',
 'Var113',
 'Var114',
 'Var115',
 'Var116',
 'Var117',
 'Var118',
 'Var119',
 'Var120',
 'Var121',
 'Var122',
 'Var123',
 'Var124',
 'Var125',
 'Var126',
 'Var127',
 'Var128',
 'Var129',
 'Var130',
 'Var131',
 'Var132',
 'Var133',
 'Var134',
 'Var135',
 'Var136',
 'Var137',
 'Var138',
 'Var139',
 'Var140',
 'Var141',
 'Var142',
 'Var143',
 'Var144',
 'Var145',
 'Var146',
 'Var147',
 'Var148',
 'Var149',
 'Var150',
 'Var151',
 'Var152',
 'Var153',
 'Var154',
 'Var155',
 'Var156',
 'Var157',
 'Var158',
 'Var159',
 'Var160',
 'Var161',
 'Var162',
 'Var163',
 'Var164',
 'Var165',
 'Var166',
 'Var167',
 'Var168',
 'Var169',
 'Var170',
 'Var171',
 'Var172',
 'Var173',
 'Var174',
 'Var175',
 'Var176',
 'Var177',
 'Var178',
 'Var179',
 'Var180',
 'Var181',
 'Var182',
 'Var183',
 'Var184',
 'Var185',
 'Var186',
 'Var187',
 'Var188',
 'Var189',
 'Var190',
 'Var209',
 'Var230',
 'y']

In [3]:
cat_cols = df.drop(columns=num_cols).columns.tolist()
cat_cols

['Var191',
 'Var192',
 'Var193',
 'Var194',
 'Var195',
 'Var196',
 'Var197',
 'Var198',
 'Var199',
 'Var200',
 'Var201',
 'Var202',
 'Var203',
 'Var204',
 'Var205',
 'Var206',
 'Var207',
 'Var208',
 'Var210',
 'Var211',
 'Var212',
 'Var213',
 'Var214',
 'Var215',
 'Var216',
 'Var217',
 'Var218',
 'Var219',
 'Var220',
 'Var221',
 'Var222',
 'Var223',
 'Var224',
 'Var225',
 'Var226',
 'Var227',
 'Var228',
 'Var229']

In [4]:
from home_works.machine_learning.final_project.util import get_nan_percentage

allowed_columns = df.loc[:, get_nan_percentage(df) < 35].columns.tolist()

df_cleaned = df[allowed_columns]
df_cleaned.head()

,Var6,Var7,Var13,Var21,Var22,Var24,Var25,Var28,Var35,Var38,...,Var218,Var219,Var220,Var221,Var222,Var223,Var226,Var227,Var228,y
0,812.0,14.0,1252.0,156.0,195.0,0.0,40.0,286.96,0.0,4850466.0,...,cJvF,AU8_WTd,4UxGlow,zCkv,catzS2D,jySVZNlOJy,Aoh3,ZI9m,ib5G6X1eUxUn6,0
1,2688.0,7.0,8820.0,364.0,455.0,4.0,288.0,200.00,0.0,132072.0,...,UYBR,AU8pNoi,GpvRJ5l,oslk,i06ocsg,LM8l689qOp,WqMG,RAYp,55YFVY9,0
2,1015.0,14.0,1784.0,136.0,170.0,2.0,40.0,294.48,0.0,3223524.0,...,cJvF,FzaX,ch2oGfM,zCkv,P6pu4Vl,LM8l689qOp,Aoh3,ZI9m,R4y5gQQWY8OodqDV,0
3,168.0,0.0,0.0,24.0,30.0,0.0,0.0,644.24,0.0,2135430.0,...,cJvF,FzaX,kH5mFX7,oslk,BNrD3Yd,LM8l689qOp,FSa2,RAYp,F2FyR07IdsN7I,0
4,14.0,0.0,0.0,36.0,45.0,0.0,0.0,239.84,0.0,3110400.0,...,cJvF,FzaX,x_lYlW4,oslk,3B1QowC,LM8l689qOp,WqMG,RAYp,F2FyR07IdsN7I,0

In [5]:
from home_works.machine_learning.final_project.util import split_df_to_x_y

X, y = split_df_to_x_y(df_cleaned, "y")

In [6]:
from sklearn.pipeline import Pipeline
from home_works.machine_learning.final_project.util import VarMeanEstimator
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

original_num_cols = num_cols
num_cols = [c for c in num_cols if c in X.columns]

num_data_prep = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
    ("var_mean", VarMeanEstimator(col_name="VarMean", cols_to_mean=num_cols))
])

num_data_prep.set_output(transform="pandas")

num_data_scaled = num_data_prep.fit_transform(X[num_cols])

num_data_scaled.head()

,Var6,Var7,Var13,Var21,Var22,Var24,Var25,Var28,Var35,Var38,...,Var140,Var143,Var144,Var149,Var153,Var160,Var163,Var173,Var181,VarMean
0,-0.212337,1.192359,0.017317,-0.142524,-0.140019,-0.488119,-0.263571,0.641706,-0.228852,0.817387,...,-0.291121,-0.085463,1.354143,-0.389478,1.040498,-0.086067,-0.553093,-0.046956,-0.225677,0.189345
1,0.617608,0.020968,2.832081,0.253591,0.255808,-0.024392,0.943577,-0.252876,-0.228852,-0.804485,...,-0.408379,-0.085463,-0.223836,0.216229,-0.984923,-0.198993,0.063617,-0.046956,-0.225677,0.101319
2,-0.122530,1.192359,0.215183,-0.180612,-0.178080,-0.256256,-0.263571,0.719067,-0.228852,0.258152,...,1.487849,-0.085463,1.354143,0.454210,1.007088,-0.131238,0.611261,-0.046956,-0.225677,0.200151
3,-0.497243,-1.150423,-0.448339,-0.393904,-0.391218,-0.488119,-0.458272,4.317150,-0.228852,-0.115863,...,-0.428480,-0.085463,-0.223836,-0.389478,1.202683,-0.379674,-0.553093,-0.046956,-0.225677,0.052917
4,-0.565373,-1.150423,-0.448339,-0.371052,-0.368381,-0.488119,-0.458272,0.156969,-0.228852,0.219268,...,-0.428480,-0.085463,-1.012826,-0.389478,-0.840864,-0.402259,-0.553093,-0.046956,-0.225677,-0.380261

In [7]:
from home_works.machine_learning.final_project.util import CategoryHasher

original_cat_cols = cat_cols
cat_cols = [c for c in original_cat_cols if c in X.columns]

cat_prep = Pipeline(
    steps=[
        ("target_encoder", TargetEncoder(cols=cat_cols)),
    ]
)

cat_prep.set_output(transform="pandas")

cat_preped = cat_prep.fit_transform(X[cat_cols], y)

cat_preped.head()

,Var192,Var193,Var195,Var196,Var197,Var198,Var199,Var202,Var203,Var204,...,Var217,Var218,Var219,Var220,Var221,Var222,Var223,Var226,Var227,Var228
0,0.125146,0.000001,0.134499,0.130097,0.103166,0.001046,0.220072,0.161831,0.129382,0.103960,...,0.161831,0.103809,0.042021,0.001046,0.046923,0.001046,0.103865,0.107422,0.010355,0.001764
1,0.050972,0.000635,0.134499,0.130097,0.125277,0.100292,0.200129,0.167548,0.129382,0.148148,...,0.194728,0.152126,0.086294,0.100292,0.167083,0.100292,0.130565,0.138601,0.175847,0.000000
2,0.111988,0.179612,0.134499,0.130097,0.133047,0.016216,0.103704,0.137654,0.129382,0.103960,...,0.143179,0.103809,0.131214,0.016216,0.046923,0.016216,0.130565,0.107422,0.010355,0.042614
3,0.147775,0.179612,0.134499,0.130097,0.133047,0.208904,0.197888,0.179664,0.129382,0.162896,...,0.161831,0.103809,0.131214,0.208904,0.167083,0.208904,0.130565,0.177008,0.175847,0.193027
4,0.054165,0.179612,0.134499,0.130097,0.140250,0.102551,0.209801,0.111988,0.129382,0.123711,...,0.111988,0.103809,0.131214,0.102551,0.167083,0.102551,0.130565,0.138601,0.175847,0.193027

In [8]:
from home_works.machine_learning.final_project.util import concat_dfs

X_final = concat_dfs(num_data_scaled, cat_preped)
X_final.head()

,Var6,Var7,Var13,Var21,Var22,Var24,Var25,Var28,Var35,Var38,...,Var217,Var218,Var219,Var220,Var221,Var222,Var223,Var226,Var227,Var228
0,-0.212337,1.192359,0.017317,-0.142524,-0.140019,-0.488119,-0.263571,0.641706,-0.228852,0.817387,...,0.161831,0.103809,0.042021,0.001046,0.046923,0.001046,0.103865,0.107422,0.010355,0.001764
1,0.617608,0.020968,2.832081,0.253591,0.255808,-0.024392,0.943577,-0.252876,-0.228852,-0.804485,...,0.194728,0.152126,0.086294,0.100292,0.167083,0.100292,0.130565,0.138601,0.175847,0.000000
2,-0.122530,1.192359,0.215183,-0.180612,-0.178080,-0.256256,-0.263571,0.719067,-0.228852,0.258152,...,0.143179,0.103809,0.131214,0.016216,0.046923,0.016216,0.130565,0.107422,0.010355,0.042614
3,-0.497243,-1.150423,-0.448339,-0.393904,-0.391218,-0.488119,-0.458272,4.317150,-0.228852,-0.115863,...,0.161831,0.103809,0.131214,0.208904,0.167083,0.208904,0.130565,0.177008,0.175847,0.193027
4,-0.565373,-1.150423,-0.448339,-0.371052,-0.368381,-0.488119,-0.458272,0.156969,-0.228852,0.219268,...,0.111988,0.103809,0.131214,0.102551,0.167083,0.102551,0.130565,0.138601,0.175847,0.193027

In [9]:
from home_works.machine_learning.final_project.util import HyperParametersOptimizer

best_params = HyperParametersOptimizer(X_final, y).catboost_objective(n_trials=100)

best_params

[I 2025-11-24 10:39:32,767] A new study created in memory with name: no-name-9eb51d24-dab6-4ce3-ae99-f1501a7662b4
[I 2025-11-24 10:39:46,007] Trial 0 finished with value: 0.8115015786121477 and parameters: {'n_estimators': 874, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 8, 'max_features': 'log2', 'replacement': True, 'sampling_strategy': 'all'}. Best is trial 0 with value: 0.8115015786121477.
[I 2025-11-24 10:39:52,806] Trial 1 finished with value: 0.8918623908002704 and parameters: {'n_estimators': 335, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'replacement': True, 'sampling_strategy': 'auto'}. Best is trial 1 with value: 0.8918623908002704.
[I 2025-11-24 10:41:30,650] Trial 2 finished with value: 0.8953424200790122 and parameters: {'n_estimators': 678, 'max_depth': 12, 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_features': None, 'replacement': True, 'sampling_strategy': 'auto'}. Best is trial 2 with value: 0.8953424200790122.
[I 2025-11-24 10:41:41,482] Trial 3 finished with value: 0.8673604629584096 and parameters: {'n_estimators': 590, 'max_depth': 6, 'min_samples_split': 11, 'min_samples_leaf': 10, 'max_features': 'sqrt', 'replacement': True, 'sampling_strategy': 'all'}. Best is trial 2 with value: 0.8953424200790122.
[I 2025-11-24 10:42:14,005] Trial 4 finished with value: 0.8990018138077867 and parameters: {'n_estimators': 207, 'max_depth': 11, 'min_samples_split': 14, 'min_samples_leaf': 1, 'max_features': None, 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 4 with value: 0.8990018138077867.
[I 2025-11-24 10:42:42,688] Trial 5 finished with value: 0.8817016151545272 and parameters: {'n_estimators': 212, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 1, 'max_features': None, 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 4 with value: 0.8990018138077867.
[I 2025-11-24 10:42:53,946] Trial 6 finished with value: 0.7853658620467341 and parameters: {'n_estimators': 849, 'max_depth': 4, 'min_samples_split': 7, 'min_samples_leaf': 1, 'max_features': 'log2', 'replacement': True, 'sampling_strategy': 'all'}. Best is trial 4 with value: 0.8990018138077867.
[I 2025-11-24 10:44:14,045] Trial 7 finished with value: 0.8780542047220455 and parameters: {'n_estimators': 775, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 9, 'max_features': None, 'replacement': False, 'sampling_strategy': 'all'}. Best is trial 4 with value: 0.8990018138077867.
[I 2025-11-24 10:44:23,666] Trial 8 finished with value: 0.8673122965878383 and parameters: {'n_estimators': 542, 'max_depth': 8, 'min_samples_split': 12, 'min_samples_leaf': 10, 'max_features': 'log2', 'replacement': True, 'sampling_strategy': 'auto'}. Best is trial 4 with value: 0.8990018138077867.
[I 2025-11-24 10:44:33,985] Trial 9 finished with value: 0.8936172799370687 and parameters: {'n_estimators': 434, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'replacement': False, 'sampling_strategy': 'all'}. Best is trial 4 with value: 0.8990018138077867.
[I 2025-11-24 10:45:06,612] Trial 10 finished with value: 0.9029303019450822 and parameters: {'n_estimators': 219, 'max_depth': 12, 'min_samples_split': 15, 'min_samples_leaf': 3, 'max_features': None, 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 10 with value: 0.9029303019450822.
[I 2025-11-24 10:45:36,558] Trial 11 finished with value: 0.9023610193409557 and parameters: {'n_estimators': 201, 'max_depth': 12, 'min_samples_split': 15, 'min_samples_leaf': 3, 'max_features': None, 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 10 with value: 0.9029303019450822.
[I 2025-11-24 10:46:25,489] Trial 12 finished with value: 0.8992192267670205 and parameters: {'n_estimators': 354, 'max_depth': 10, 'min_samples_split': 15, 'min_samples_leaf': 4, 'max_features': None, 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 10 with value: 0.9029303019450822.
[I 2025-11-24 10:47:15,114] Trial 13 finished with value: 0.9037768124922003 and parameters: {'n_estimators': 330, 'max_depth': 12, 'min_samples_split': 12, 'min_samples_leaf': 3, 'max_features': None, 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 13 with value: 0.9037768124922003.
[I 2025-11-24 10:48:15,012] Trial 14 finished with value: 0.8925757170989354 and parameters: {'n_estimators': 449, 'max_depth': 10, 'min_samples_split': 11, 'min_samples_leaf': 6, 'max_features': None, 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 13 with value: 0.9037768124922003.
[I 2025-11-24 10:49:05,015] Trial 15 finished with value: 0.9031332233662266 and parameters: {'n_estimators': 336, 'max_depth': 12, 'min_samples_split': 13, 'min_samples_leaf': 3, 'max_features': None, 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 13 with value: 0.9037768124922003.
[I 2025-11-24 10:49:56,315] Trial 16 finished with value: 0.8975191675845599 and parameters: {'n_estimators': 380, 'max_depth': 9, 'min_samples_split': 12, 'min_samples_leaf': 3, 'max_features': None, 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 13 with value: 0.9037768124922003.
[I 2025-11-24 10:50:27,523] Trial 17 finished with value: 0.8116596648932004 and parameters: {'n_estimators': 507, 'max_depth': 3, 'min_samples_split': 13, 'min_samples_leaf': 5, 'max_features': None, 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 13 with value: 0.9037768124922003.
[I 2025-11-24 10:50:51,081] Trial 18 finished with value: 0.8977204300266864 and parameters: {'n_estimators': 965, 'max_depth': 11, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 13 with value: 0.9037768124922003.
[I 2025-11-24 10:50:57,168] Trial 19 finished with value: 0.8873745018841952 and parameters: {'n_estimators': 304, 'max_depth': 11, 'min_samples_split': 10, 'min_samples_leaf': 6, 'max_features': 'log2', 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 13 with value: 0.9037768124922003.
[I 2025-11-24 10:52:36,233] Trial 20 finished with value: 0.8950582986267579 and parameters: {'n_estimators': 706, 'max_depth': 9, 'min_samples_split': 13, 'min_samples_leaf': 2, 'max_features': None, 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 13 with value: 0.9037768124922003.
[I 2025-11-24 10:53:18,697] Trial 21 finished with value: 0.903860450070234 and parameters: {'n_estimators': 285, 'max_depth': 12, 'min_samples_split': 14, 'min_samples_leaf': 3, 'max_features': None, 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 21 with value: 0.903860450070234.
[I 2025-11-24 10:53:59,984] Trial 22 finished with value: 0.8992397102319061 and parameters: {'n_estimators': 287, 'max_depth': 12, 'min_samples_split': 13, 'min_samples_leaf': 5, 'max_features': None, 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 21 with value: 0.903860450070234.
[I 2025-11-24 10:55:09,622] Trial 23 finished with value: 0.9029826739872704 and parameters: {'n_estimators': 455, 'max_depth': 11, 'min_samples_split': 14, 'min_samples_leaf': 2, 'max_features': None, 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 21 with value: 0.903860450070234.
[I 2025-11-24 10:56:07,783] Trial 24 finished with value: 0.9025533659029488 and parameters: {'n_estimators': 390, 'max_depth': 12, 'min_samples_split': 10, 'min_samples_leaf': 3, 'max_features': None, 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 21 with value: 0.903860450070234.
[I 2025-11-24 10:56:44,740] Trial 25 finished with value: 0.8958408277319009 and parameters: {'n_estimators': 276, 'max_depth': 9, 'min_samples_split': 12, 'min_samples_leaf': 4, 'max_features': None, 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 21 with value: 0.903860450070234.
[I 2025-11-24 10:57:58,642] Trial 26 finished with value: 0.8997829705829108 and parameters: {'n_estimators': 502, 'max_depth': 10, 'min_samples_split': 14, 'min_samples_leaf': 2, 'max_features': None, 'replacement': False, 'sampling_strategy': 'all'}. Best is trial 21 with value: 0.903860450070234.
[I 2025-11-24 10:58:38,225] Trial 27 finished with value: 0.9033042570157844 and parameters: {'n_estimators': 270, 'max_depth': 11, 'min_samples_split': 9, 'min_samples_leaf': 3, 'max_features': None, 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 21 with value: 0.903860450070234.
[I 2025-11-24 10:58:44,420] Trial 28 finished with value: 0.8960336187545745 and parameters: {'n_estimators': 257, 'max_depth': 11, 'min_samples_split': 9, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 21 with value: 0.903860450070234.
[I 2025-11-24 10:58:56,078] Trial 29 finished with value: 0.8856893529178993 and parameters: {'n_estimators': 615, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 8, 'max_features': 'log2', 'replacement': True, 'sampling_strategy': 'all'}. Best is trial 21 with value: 0.903860450070234.
[I 2025-11-24 10:59:04,126] Trial 30 finished with value: 0.8924244289773933 and parameters: {'n_estimators': 403, 'max_depth': 10, 'min_samples_split': 9, 'min_samples_leaf': 4, 'max_features': 'log2', 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 21 with value: 0.903860450070234.
[I 2025-11-24 10:59:52,030] Trial 31 finished with value: 0.9038306927068115 and parameters: {'n_estimators': 321, 'max_depth': 12, 'min_samples_split': 11, 'min_samples_leaf': 3, 'max_features': None, 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 21 with value: 0.903860450070234.
[I 2025-11-24 11:00:36,353] Trial 32 finished with value: 0.9029990765857813 and parameters: {'n_estimators': 282, 'max_depth': 12, 'min_samples_split': 11, 'min_samples_leaf': 2, 'max_features': None, 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 21 with value: 0.903860450070234.
[I 2025-11-24 11:01:24,338] Trial 33 finished with value: 0.9028838331359681 and parameters: {'n_estimators': 329, 'max_depth': 11, 'min_samples_split': 11, 'min_samples_leaf': 3, 'max_features': None, 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 21 with value: 0.903860450070234.
[I 2025-11-24 11:02:00,961] Trial 34 finished with value: 0.8949914150491768 and parameters: {'n_estimators': 255, 'max_depth': 12, 'min_samples_split': 12, 'min_samples_leaf': 4, 'max_features': None, 'replacement': True, 'sampling_strategy': 'auto'}. Best is trial 21 with value: 0.903860450070234.
[I 2025-11-24 11:02:09,535] Trial 35 finished with value: 0.8955899823660525 and parameters: {'n_estimators': 349, 'max_depth': 12, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 21 with value: 0.903860450070234.
[I 2025-11-24 11:02:59,082] Trial 36 finished with value: 0.8790490261444214 and parameters: {'n_estimators': 401, 'max_depth': 7, 'min_samples_split': 9, 'min_samples_leaf': 1, 'max_features': None, 'replacement': True, 'sampling_strategy': 'auto'}. Best is trial 21 with value: 0.903860450070234.
[I 2025-11-24 11:03:34,662] Trial 37 finished with value: 0.9005037761734546 and parameters: {'n_estimators': 247, 'max_depth': 11, 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_features': None, 'replacement': False, 'sampling_strategy': 'all'}. Best is trial 21 with value: 0.903860450070234.
[I 2025-11-24 11:04:03,540] Trial 38 finished with value: 0.8723708018966633 and parameters: {'n_estimators': 306, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': None, 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 21 with value: 0.903860450070234.
[I 2025-11-24 11:05:29,417] Trial 39 finished with value: 0.8856701488718816 and parameters: {'n_estimators': 605, 'max_depth': 9, 'min_samples_split': 14, 'min_samples_leaf': 1, 'max_features': None, 'replacement': True, 'sampling_strategy': 'auto'}. Best is trial 21 with value: 0.903860450070234.
[I 2025-11-24 11:05:40,572] Trial 40 finished with value: 0.8940006629628025 and parameters: {'n_estimators': 501, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'replacement': False, 'sampling_strategy': 'all'}. Best is trial 21 with value: 0.903860450070234.
[I 2025-11-24 11:06:29,651] Trial 41 finished with value: 0.9031391175093717 and parameters: {'n_estimators': 330, 'max_depth': 12, 'min_samples_split': 13, 'min_samples_leaf': 3, 'max_features': None, 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 21 with value: 0.903860450070234.
[I 2025-11-24 11:07:15,025] Trial 42 finished with value: 0.9015231274673472 and parameters: {'n_estimators': 312, 'max_depth': 12, 'min_samples_split': 12, 'min_samples_leaf': 4, 'max_features': None, 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 21 with value: 0.903860450070234.
[I 2025-11-24 11:07:49,417] Trial 43 finished with value: 0.90262976710041 and parameters: {'n_estimators': 235, 'max_depth': 11, 'min_samples_split': 11, 'min_samples_leaf': 3, 'max_features': None, 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 21 with value: 0.903860450070234.
[I 2025-11-24 11:08:48,445] Trial 44 finished with value: 0.9031313301436968 and parameters: {'n_estimators': 372, 'max_depth': 12, 'min_samples_split': 8, 'min_samples_leaf': 2, 'max_features': None, 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 21 with value: 0.903860450070234.
[I 2025-11-24 11:08:58,042] Trial 45 finished with value: 0.8948915744097029 and parameters: {'n_estimators': 465, 'max_depth': 11, 'min_samples_split': 14, 'min_samples_leaf': 1, 'max_features': 'log2', 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 21 with value: 0.903860450070234.
[I 2025-11-24 11:09:57,744] Trial 46 finished with value: 0.9006462516783784 and parameters: {'n_estimators': 422, 'max_depth': 10, 'min_samples_split': 13, 'min_samples_leaf': 3, 'max_features': None, 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 21 with value: 0.903860450070234.
[I 2025-11-24 11:10:27,383] Trial 47 finished with value: 0.8944296436611218 and parameters: {'n_estimators': 207, 'max_depth': 12, 'min_samples_split': 15, 'min_samples_leaf': 4, 'max_features': None, 'replacement': True, 'sampling_strategy': 'auto'}. Best is trial 21 with value: 0.903860450070234.
[I 2025-11-24 11:11:45,819] Trial 48 finished with value: 0.895608729376287 and parameters: {'n_estimators': 561, 'max_depth': 12, 'min_samples_split': 11, 'min_samples_leaf': 6, 'max_features': None, 'replacement': False, 'sampling_strategy': 'all'}. Best is trial 21 with value: 0.903860450070234.
[I 2025-11-24 11:12:23,796] Trial 49 finished with value: 0.8789241056894024 and parameters: {'n_estimators': 352, 'max_depth': 6, 'min_samples_split': 13, 'min_samples_leaf': 3, 'max_features': None, 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 21 with value: 0.903860450070234.
[I 2025-11-24 11:14:19,260] Trial 50 finished with value: 0.8915914682488186 and parameters: {'n_estimators': 844, 'max_depth': 11, 'min_samples_split': 12, 'min_samples_leaf': 7, 'max_features': None, 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 21 with value: 0.903860450070234.
[I 2025-11-24 11:15:09,131] Trial 51 finished with value: 0.9028106224749944 and parameters: {'n_estimators': 331, 'max_depth': 12, 'min_samples_split': 13, 'min_samples_leaf': 3, 'max_features': None, 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 21 with value: 0.903860450070234.
[I 2025-11-24 11:15:51,683] Trial 52 finished with value: 0.9036204518703886 and parameters: {'n_estimators': 272, 'max_depth': 12, 'min_samples_split': 14, 'min_samples_leaf': 2, 'max_features': None, 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 21 with value: 0.903860450070234.
[I 2025-11-24 11:16:34,217] Trial 53 finished with value: 0.9036480535693074 and parameters: {'n_estimators': 273, 'max_depth': 12, 'min_samples_split': 15, 'min_samples_leaf': 2, 'max_features': None, 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 21 with value: 0.903860450070234.
[I 2025-11-24 11:17:10,974] Trial 54 finished with value: 0.8982912428476826 and parameters: {'n_estimators': 233, 'max_depth': 11, 'min_samples_split': 15, 'min_samples_leaf': 1, 'max_features': None, 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 21 with value: 0.903860450070234.
[I 2025-11-24 11:17:53,652] Trial 55 finished with value: 0.9039690360548283 and parameters: {'n_estimators': 274, 'max_depth': 12, 'min_samples_split': 15, 'min_samples_leaf': 2, 'max_features': None, 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 55 with value: 0.9039690360548283.
[I 2025-11-24 11:18:01,016] Trial 56 finished with value: 0.8959203552002224 and parameters: {'n_estimators': 292, 'max_depth': 12, 'min_samples_split': 15, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 55 with value: 0.9039690360548283.
[I 2025-11-24 11:18:31,608] Trial 57 finished with value: 0.8942453877318824 and parameters: {'n_estimators': 201, 'max_depth': 10, 'min_samples_split': 14, 'min_samples_leaf': 1, 'max_features': None, 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 55 with value: 0.9039690360548283.
[I 2025-11-24 11:18:36,194] Trial 58 finished with value: 0.7569615037123183 and parameters: {'n_estimators': 369, 'max_depth': 3, 'min_samples_split': 15, 'min_samples_leaf': 2, 'max_features': 'log2', 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 55 with value: 0.9039690360548283.
[I 2025-11-24 11:20:21,230] Trial 59 finished with value: 0.9029890239581654 and parameters: {'n_estimators': 670, 'max_depth': 12, 'min_samples_split': 14, 'min_samples_leaf': 2, 'max_features': None, 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 55 with value: 0.9039690360548283.
[I 2025-11-24 11:20:38,453] Trial 60 finished with value: 0.8530909924348069 and parameters: {'n_estimators': 230, 'max_depth': 4, 'min_samples_split': 15, 'min_samples_leaf': 2, 'max_features': None, 'replacement': True, 'sampling_strategy': 'all'}. Best is trial 55 with value: 0.9039690360548283.
[I 2025-11-24 11:21:20,297] Trial 61 finished with value: 0.90259999191809 and parameters: {'n_estimators': 273, 'max_depth': 11, 'min_samples_split': 14, 'min_samples_leaf': 2, 'max_features': None, 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 55 with value: 0.9039690360548283.
[I 2025-11-24 11:22:00,010] Trial 62 finished with value: 0.9035138619550936 and parameters: {'n_estimators': 265, 'max_depth': 12, 'min_samples_split': 15, 'min_samples_leaf': 3, 'max_features': None, 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 55 with value: 0.9039690360548283.
[I 2025-11-24 11:22:41,959] Trial 63 finished with value: 0.9008673026520002 and parameters: {'n_estimators': 257, 'max_depth': 12, 'min_samples_split': 15, 'min_samples_leaf': 1, 'max_features': None, 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 55 with value: 0.9039690360548283.
[I 2025-11-24 11:23:27,362] Trial 64 finished with value: 0.9019236852950753 and parameters: {'n_estimators': 313, 'max_depth': 12, 'min_samples_split': 14, 'min_samples_leaf': 4, 'max_features': None, 'replacement': False, 'sampling_strategy': 'auto'}. Best is trial 55 with value: 0.9039690360548283.

{'n_estimators': 431,
 'max_depth': 11,
 'min_samples_split': 8,
 'min_samples_leaf': 2,
 'max_features': None,
 'replacement': True,
 'sampling_strategy': 'all'}

In [10]:
from imblearn.ensemble import BalancedRandomForestClassifier

model = BalancedRandomForestClassifier(**best_params)

In [11]:
from home_works.machine_learning.final_project.util import evaluate_model_avg_accuracy

evaluate_model_avg_accuracy(model, X_final, y)

Точність для кожного фолду: [0.976  0.974  0.9755 0.964  0.975 ]
Середня точність: 0.9728999999999999

In [12]:
from home_works.machine_learning.final_project.util import evaluate_model, split_train_test

X_train, X_test, y_train, y_test = split_train_test(X_final, y)
evaluate_model(model, X_train, y_train, X_test, y_test)

Звіт для порогу 0.4:
              precision    recall  f1-score   support

           0       0.99      0.98      0.99      1737
           1       0.90      0.96      0.93       263

    accuracy                           0.98      2000
   macro avg       0.95      0.97      0.96      2000
weighted avg       0.98      0.98      0.98      2000

In [15]:
final_model = BalancedRandomForestClassifier(**best_params)
final_model.fit(X_final, y)

BalancedRandomForestClassifier(max_depth=11, max_features=None,
                               min_samples_leaf=2, min_samples_split=8,
                               n_estimators=431)

In [16]:
validation_data = read_csv("ml-fundamentals-and-applications-2025-10/final_proj_test.csv")

validation_data.head()

,Var1,Var2,Var3,Var4,Var5,Var6,Var7,Var8,Var9,Var10,...,Var221,Var222,Var223,Var224,Var225,Var226,Var227,Var228,Var229,Var230
0,NaN,NaN,NaN,NaN,NaN,819.0,7.0,NaN,NaN,NaN,...,zCkv,catzS2D,LM8l689qOp,NaN,ELof,rgKb,ZI9m,ib5G6X1eUxUn6,am7c,NaN
1,NaN,NaN,NaN,NaN,NaN,3192.0,28.0,NaN,NaN,NaN,...,oslk,QkgQQMs,LM8l689qOp,NaN,NaN,453m,RAYp,F2FyR07IdsN7I,am7c,NaN
2,NaN,NaN,NaN,NaN,NaN,756.0,0.0,NaN,NaN,NaN,...,oslk,bxCQb98,jySVZNlOJy,NaN,NaN,Qu4f,RAYp,F2FyR07IdsN7I,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,3892.0,21.0,NaN,NaN,NaN,...,oslk,0JeRt72,M_8D,NaN,ELof,Aoh3,RAYp,F2FyR07IdsN7I,mj86,NaN
4,NaN,NaN,NaN,NaN,NaN,672.0,7.0,NaN,NaN,NaN,...,oslk,0p8OTZB,LM8l689qOp,NaN,ELof,xb3V,RAYp,F2FyR07IdsN7I,mj86,NaN

In [17]:
allowed_columns.remove("y")
df_cleaned_final = validation_data[allowed_columns]
df_cleaned_final.head()

,Var6,Var7,Var13,Var21,Var22,Var24,Var25,Var28,Var35,Var38,...,Var217,Var218,Var219,Var220,Var221,Var222,Var223,Var226,Var227,Var228
0,819.0,7.0,0.0,160.0,200.0,2.0,56.0,403.36,0.0,4800036.0,...,6ITF,cJvF,FzaX,4UxGlow,zCkv,catzS2D,LM8l689qOp,rgKb,ZI9m,ib5G6X1eUxUn6
1,3192.0,28.0,3864.0,380.0,475.0,8.0,288.0,200.00,0.0,51282.0,...,RRN_,UYBR,FzaX,k5O88FJ,oslk,QkgQQMs,LM8l689qOp,453m,RAYp,F2FyR07IdsN7I
2,756.0,0.0,0.0,156.0,195.0,2.0,40.0,402.24,0.0,3462336.0,...,c4pP,UYBR,FzaX,h72uX8Z,oslk,bxCQb98,jySVZNlOJy,Qu4f,RAYp,F2FyR07IdsN7I
3,3892.0,21.0,5192.0,152.0,190.0,0.0,8.0,212.08,0.0,7331880.0,...,fgNW,UYBR,FzaX,VA_88FJ,oslk,0JeRt72,M_8D,Aoh3,RAYp,F2FyR07IdsN7I
4,672.0,7.0,16.0,144.0,180.0,2.0,64.0,322.64,0.0,381480.0,...,dvCm,UYBR,FzaX,FB4YlW4,oslk,0p8OTZB,LM8l689qOp,xb3V,RAYp,F2FyR07IdsN7I

In [18]:
num_cols_final = df_cleaned_final.select_dtypes(include=["number"]).columns.tolist()

df_cleaned_final[num_cols_final].head()

,Var6,Var7,Var13,Var21,Var22,Var24,Var25,Var28,Var35,Var38,...,Var134,Var140,Var143,Var144,Var149,Var153,Var160,Var163,Var173,Var181
0,819.0,7.0,0.0,160.0,200.0,2.0,56.0,403.36,0.0,4800036.0,...,807760.0,20.0,0.0,18.0,554435.0,10948360.0,22.0,0.0,0.0,0.0
1,3192.0,28.0,3864.0,380.0,475.0,8.0,288.0,200.00,0.0,51282.0,...,327752.0,1835.0,0.0,9.0,280392.0,2101956.0,46.0,375756.0,0.0,0.0
2,756.0,0.0,0.0,156.0,195.0,2.0,40.0,402.24,0.0,3462336.0,...,796264.0,0.0,0.0,9.0,554400.0,10325800.0,26.0,475200.0,0.0,0.0
3,3892.0,21.0,5192.0,152.0,190.0,0.0,8.0,212.08,0.0,7331880.0,...,13754.0,2905.0,0.0,0.0,0.0,10596480.0,18.0,0.0,0.0,0.0
4,672.0,7.0,16.0,144.0,180.0,2.0,64.0,322.64,0.0,381480.0,...,104290.0,430.0,0.0,27.0,46963.0,2004852.0,42.0,40254.0,0.0,7.0

In [19]:
cat_cols_final = df_cleaned_final.drop(columns=num_cols_final).columns.tolist()
df_cleaned_final[cat_cols_final].head()

,Var192,Var193,Var195,Var196,Var197,Var198,Var199,Var202,Var203,Var204,...,Var217,Var218,Var219,Var220,Var221,Var222,Var223,Var226,Var227,Var228
0,75lTmBtFkL,rEUOq2QD1qfkRr6qpua,taul,1K8T,F9g8,fhk21Ss,GVWDufEPyV,GHne,9_Y1,c2JP,...,6ITF,cJvF,FzaX,4UxGlow,zCkv,catzS2D,LM8l689qOp,rgKb,ZI9m,ib5G6X1eUxUn6
1,1YVgUHXZeb,RO12,taul,1K8T,0Xwj,Ml6kiFp,S85OeCBjSz,14hG,HLqf,8BBI,...,RRN_,UYBR,FzaX,k5O88FJ,oslk,QkgQQMs,LM8l689qOp,453m,RAYp,F2FyR07IdsN7I
2,cFHt0GoOh3,RO12,taul,1K8T,wGW5,Wq69B7S,z7GH4Up,dK_l,9_Y1,rGJy,...,c4pP,UYBR,FzaX,h72uX8Z,oslk,bxCQb98,jySVZNlOJy,Qu4f,RAYp,F2FyR07IdsN7I
3,m9SrEy7Rm6,RO12,taul,1K8T,JLbT,4JEMGuV,oQ173939hSRjL,zqqA,9_Y1,X8zP,...,fgNW,UYBR,FzaX,VA_88FJ,oslk,0JeRt72,M_8D,Aoh3,RAYp,F2FyR07IdsN7I
4,BQavyxLp3Z,RO12,taul,1K8T,lK27,32pCIek,JQFeOYK,YqMO,9_Y1,_r21,...,dvCm,UYBR,FzaX,FB4YlW4,oslk,0p8OTZB,LM8l689qOp,xb3V,RAYp,F2FyR07IdsN7I

In [20]:
# Використовуємо .transform(), а не .fit_transform().
# Пайплайни вже "навчені" на X та y вище. Тепер ми просто застосовуємо знання до нових даних.

# 1. Числові дані: Тільки transform
num_data_scaled_final = num_data_prep.transform(df_cleaned_final[num_cols_final])
num_data_scaled_final.head()

/Users/kozak_mamay/PycharmProjects/WoolfDataScience/.venv/lib/python3.12/site-packages/sklearn/pipeline.py:61: FutureWarning: This Pipeline instance is not fitted yet. Call 'fit' with appropriate arguments before using other methods such as transform, predict, etc. This will raise an error in 1.8 instead of the current warning.
  warnings.warn(

,Var6,Var7,Var13,Var21,Var22,Var24,Var25,Var28,Var35,Var38,...,Var140,Var143,Var144,Var149,Var153,Var160,Var163,Var173,Var181,VarMean
0,-0.209240,0.020968,-0.448339,-0.134906,-0.132407,-0.256256,-0.185691,1.839147,-0.228852,0.800053,...,-0.421779,-0.085463,0.565153,0.454232,1.103946,-0.176408,-0.553093,-0.046956,-0.225677,0.109084
1,0.840578,3.535141,0.988797,0.284062,0.286256,0.439335,0.943577,-0.252876,-0.228852,-0.832255,...,0.186286,-0.085463,-0.223836,0.037207,-1.015704,0.094614,-0.092764,-0.046956,-0.225677,0.247006
2,-0.237111,-1.150423,-0.448339,-0.142524,-0.140019,-0.256256,-0.263571,1.827625,-0.228852,0.340240,...,-0.428480,-0.085463,-0.223836,0.454178,0.954777,-0.131238,0.029062,-0.046956,-0.225677,-0.058631
3,1.150259,2.363750,1.482720,-0.150141,-0.147631,-0.488119,-0.419332,-0.128606,-0.228852,1.670334,...,0.544761,-0.085463,-1.012826,-0.389478,1.019633,-0.221578,-0.553093,-0.046956,-0.225677,0.179791
4,-0.274273,0.020968,-0.442389,-0.165377,-0.162856,-0.256256,-0.146750,1.008757,-0.228852,-0.718755,...,-0.284420,-0.085463,1.354143,-0.318013,-1.038970,0.049443,-0.503779,-0.046956,2.739857,-0.024432

In [21]:
# 2. Категоріальні дані: Тільки transform (y тут не потрібен)
# Також передаємо df_cleaned_final[cat_cols_final], а не просто список назв
cat_preped_final = cat_prep.transform(df_cleaned_final[cat_cols_final])

cat_preped_final.head()

,Var192,Var193,Var195,Var196,Var197,Var198,Var199,Var202,Var203,Var204,...,Var217,Var218,Var219,Var220,Var221,Var222,Var223,Var226,Var227,Var228
0,0.186809,0.000065,0.134499,0.130097,0.221757,0.001046,0.083739,0.130500,0.129382,0.153590,...,0.130500,0.103809,0.131214,0.001046,0.046923,0.001046,0.130565,0.154122,0.010355,0.001764
1,0.168718,0.179612,0.134499,0.130097,0.143165,0.146781,0.139026,0.182914,0.118976,0.132338,...,0.156739,0.152126,0.131214,0.146781,0.167083,0.146781,0.130565,0.139810,0.175847,0.193027
2,0.134454,0.179612,0.134499,0.130097,0.081382,0.182914,0.111988,0.106693,0.129382,0.148936,...,0.106693,0.152126,0.131214,0.182914,0.167083,0.182914,0.103865,0.102140,0.175847,0.193027
3,0.102266,0.179612,0.134499,0.130097,0.113208,0.171611,0.111988,0.110342,0.129382,0.138211,...,0.113521,0.152126,0.131214,0.171611,0.167083,0.171611,0.089059,0.107422,0.175847,0.193027
4,0.141625,0.179612,0.134499,0.130097,0.125277,0.208904,0.049495,0.182914,0.129382,0.097272,...,0.182914,0.152126,0.131214,0.208904,0.167083,0.208904,0.130565,0.126829,0.175847,0.193027

In [22]:
num_preped_final = num_data_prep.transform(df_cleaned_final[num_cols_final])
num_preped_final.head()

/Users/kozak_mamay/PycharmProjects/WoolfDataScience/.venv/lib/python3.12/site-packages/sklearn/pipeline.py:61: FutureWarning: This Pipeline instance is not fitted yet. Call 'fit' with appropriate arguments before using other methods such as transform, predict, etc. This will raise an error in 1.8 instead of the current warning.
  warnings.warn(

,Var6,Var7,Var13,Var21,Var22,Var24,Var25,Var28,Var35,Var38,...,Var140,Var143,Var144,Var149,Var153,Var160,Var163,Var173,Var181,VarMean
0,-0.209240,0.020968,-0.448339,-0.134906,-0.132407,-0.256256,-0.185691,1.839147,-0.228852,0.800053,...,-0.421779,-0.085463,0.565153,0.454232,1.103946,-0.176408,-0.553093,-0.046956,-0.225677,0.109084
1,0.840578,3.535141,0.988797,0.284062,0.286256,0.439335,0.943577,-0.252876,-0.228852,-0.832255,...,0.186286,-0.085463,-0.223836,0.037207,-1.015704,0.094614,-0.092764,-0.046956,-0.225677,0.247006
2,-0.237111,-1.150423,-0.448339,-0.142524,-0.140019,-0.256256,-0.263571,1.827625,-0.228852,0.340240,...,-0.428480,-0.085463,-0.223836,0.454178,0.954777,-0.131238,0.029062,-0.046956,-0.225677,-0.058631
3,1.150259,2.363750,1.482720,-0.150141,-0.147631,-0.488119,-0.419332,-0.128606,-0.228852,1.670334,...,0.544761,-0.085463,-1.012826,-0.389478,1.019633,-0.221578,-0.553093,-0.046956,-0.225677,0.179791
4,-0.274273,0.020968,-0.442389,-0.165377,-0.162856,-0.256256,-0.146750,1.008757,-0.228852,-0.718755,...,-0.284420,-0.085463,1.354143,-0.318013,-1.038970,0.049443,-0.503779,-0.046956,2.739857,-0.024432

In [23]:
df_final = concat_dfs(cat_preped_final, num_preped_final)

df_final.head()

,Var192,Var193,Var195,Var196,Var197,Var198,Var199,Var202,Var203,Var204,...,Var140,Var143,Var144,Var149,Var153,Var160,Var163,Var173,Var181,VarMean
0,0.186809,0.000065,0.134499,0.130097,0.221757,0.001046,0.083739,0.130500,0.129382,0.153590,...,-0.421779,-0.085463,0.565153,0.454232,1.103946,-0.176408,-0.553093,-0.046956,-0.225677,0.109084
1,0.168718,0.179612,0.134499,0.130097,0.143165,0.146781,0.139026,0.182914,0.118976,0.132338,...,0.186286,-0.085463,-0.223836,0.037207,-1.015704,0.094614,-0.092764,-0.046956,-0.225677,0.247006
2,0.134454,0.179612,0.134499,0.130097,0.081382,0.182914,0.111988,0.106693,0.129382,0.148936,...,-0.428480,-0.085463,-0.223836,0.454178,0.954777,-0.131238,0.029062,-0.046956,-0.225677,-0.058631
3,0.102266,0.179612,0.134499,0.130097,0.113208,0.171611,0.111988,0.110342,0.129382,0.138211,...,0.544761,-0.085463,-1.012826,-0.389478,1.019633,-0.221578,-0.553093,-0.046956,-0.225677,0.179791
4,0.141625,0.179612,0.134499,0.130097,0.125277,0.208904,0.049495,0.182914,0.129382,0.097272,...,-0.284420,-0.085463,1.354143,-0.318013,-1.038970,0.049443,-0.503779,-0.046956,2.739857,-0.024432

In [24]:
# Отримуємо правильний порядок ознак безпосередньо з навченої моделі (booster)
cols_when_model_builds = final_model.feature_names_in_

# Перевпорядковуємо df_final, щоб стовпці йшли у точній послідовності, яку очікує модель
# Це також автоматично відфільтрує зайві стовпці, якщо такі є
df_final = df_final[cols_when_model_builds]

# Тепер виконуємо передбачення без помилок
prediction_final = final_model.predict(df_final)

In [26]:
from home_works.machine_learning.final_project.util import write_submission_csv

write_submission_csv(prediction_final, "final_submission_brf.csv")